#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEC94D18F7F05997E (jr@jriddell.org)
#
Name     : plasma-desktop
Version  : 5.17.0
Release  : 38
URL      : https://download.kde.org/stable/plasma/5.17.0/plasma-desktop-5.17.0.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.17.0/plasma-desktop-5.17.0.tar.xz
Source1 : https://download.kde.org/stable/plasma/5.17.0/plasma-desktop-5.17.0.tar.xz.sig
Summary  : KDE Plasma Desktop
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.2 GPL-2.0 ICU LGPL-2.0 LGPL-2.1
Requires: plasma-desktop-bin = %{version}-%{release}
Requires: plasma-desktop-data = %{version}-%{release}
Requires: plasma-desktop-lib = %{version}-%{release}
Requires: plasma-desktop-license = %{version}-%{release}
Requires: plasma-desktop-locales = %{version}-%{release}
BuildRequires : attica-dev
BuildRequires : baloo-dev
BuildRequires : boost-dev
BuildRequires : breeze-dev
BuildRequires : breeze-icons
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules pkgconfig(glib-2.0)
BuildRequires : extra-cmake-modules pkgconfig(x11-xcb)
BuildRequires : extra-cmake-modules pkgconfig(xcb) xcb-util-cursor-dev xcb-util-image-dev xcb-util-keysyms-dev xcb-util-renderutil-dev xcb-util-wm-dev xcb-util-dev
BuildRequires : freetype-dev
BuildRequires : ibus-dev
BuildRequires : kactivities-dev
BuildRequires : kactivities-stats-dev
BuildRequires : karchive-dev
BuildRequires : kcmutils-dev
BuildRequires : kcodecs-dev
BuildRequires : kcompletion-dev
BuildRequires : kcrash-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kdeclarative-dev
BuildRequires : kded-dev
BuildRequires : kdelibs4support-dev
BuildRequires : kdesignerplugin-dev
BuildRequires : kdoctools
BuildRequires : kemoticons-dev
BuildRequires : kfilemetadata-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kguiaddons-dev
BuildRequires : kiconthemes-dev
BuildRequires : kinit-dev
BuildRequires : kirigami2-dev
BuildRequires : kitemmodels-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : knewstuff-dev
BuildRequires : knotifications-dev
BuildRequires : knotifyconfig-dev
BuildRequires : kpackage-dev
BuildRequires : kparts-dev
BuildRequires : kpeople-dev
BuildRequires : krunner-dev
BuildRequires : kscreenlocker-dev
BuildRequires : ktextwidgets-dev
BuildRequires : kunitconversion-dev
BuildRequires : kwallet-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kwin-dev
BuildRequires : kwindowsystem-dev
BuildRequires : kxmlgui-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : libXcursor-dev
BuildRequires : libXi-dev
BuildRequires : libevdev-dev
BuildRequires : libinput-dev
BuildRequires : libxcb-dev
BuildRequires : libxkbfile-dev
BuildRequires : phonon-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Concurrent)
BuildRequires : pkgconfig(Qt5DBus)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickWidgets)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5X11Extras)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(libcanberra)
BuildRequires : pkgconfig(xkeyboard-config)
BuildRequires : pkgconfig(xorg-evdev)
BuildRequires : pkgconfig(xorg-libinput)
BuildRequires : pkgconfig(xorg-synaptics)
BuildRequires : plasma-framework-dev
BuildRequires : plasma-workspace-dev
BuildRequires : pulseaudio-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : systemd-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-image-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev
BuildRequires : xorg-server-dev

%description
CHANGES V0.2
- Global keys stored by default in ~/.kde/share/config/kdeglobals
[Global Keys] group
- KKeyDialog checks new key choices against exising bindings for the widget
and against entries in .kderc [Global Keys]
- kcmkeys now has two standard kcontrol pages - one for standard desktop
accelerators and one for global keybindings.

%package bin
Summary: bin components for the plasma-desktop package.
Group: Binaries
Requires: plasma-desktop-data = %{version}-%{release}
Requires: plasma-desktop-license = %{version}-%{release}

%description bin
bin components for the plasma-desktop package.


%package data
Summary: data components for the plasma-desktop package.
Group: Data

%description data
data components for the plasma-desktop package.


%package dev
Summary: dev components for the plasma-desktop package.
Group: Development
Requires: plasma-desktop-lib = %{version}-%{release}
Requires: plasma-desktop-bin = %{version}-%{release}
Requires: plasma-desktop-data = %{version}-%{release}
Provides: plasma-desktop-devel = %{version}-%{release}
Requires: plasma-desktop = %{version}-%{release}
Requires: plasma-desktop = %{version}-%{release}

%description dev
dev components for the plasma-desktop package.


%package doc
Summary: doc components for the plasma-desktop package.
Group: Documentation

%description doc
doc components for the plasma-desktop package.


%package lib
Summary: lib components for the plasma-desktop package.
Group: Libraries
Requires: plasma-desktop-data = %{version}-%{release}
Requires: plasma-desktop-license = %{version}-%{release}

%description lib
lib components for the plasma-desktop package.


%package license
Summary: license components for the plasma-desktop package.
Group: Default

%description license
license components for the plasma-desktop package.


%package locales
Summary: locales components for the plasma-desktop package.
Group: Default

%description locales
locales components for the plasma-desktop package.


%prep
%setup -q -n plasma-desktop-5.17.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571167020
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1571167020
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plasma-desktop
cp %{_builddir}/plasma-desktop-5.17.0/COPYING %{buildroot}/usr/share/package-licenses/plasma-desktop/7c203dee3a03037da436df03c4b25b659c073976
cp %{_builddir}/plasma-desktop-5.17.0/COPYING.DOC %{buildroot}/usr/share/package-licenses/plasma-desktop/bd75d59f9d7d9731bfabdc48ecd19e704d218e38
cp %{_builddir}/plasma-desktop-5.17.0/COPYING.LGPL-2 %{buildroot}/usr/share/package-licenses/plasma-desktop/ba8966e2473a9969bdcab3dc82274c817cfd98a1
cp %{_builddir}/plasma-desktop-5.17.0/COPYING.LIB %{buildroot}/usr/share/package-licenses/plasma-desktop/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/plasma-desktop-5.17.0/applets/kimpanel/COPYING %{buildroot}/usr/share/package-licenses/plasma-desktop/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/plasma-desktop-5.17.0/applets/kimpanel/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/plasma-desktop/57c3cb6b9aee09ae2af06b0c517e2969d2f33d47
cp %{_builddir}/plasma-desktop-5.17.0/applets/kimpanel/COPYING.LIB %{buildroot}/usr/share/package-licenses/plasma-desktop/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/plasma-desktop-5.17.0/applets/kimpanel/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/plasma-desktop/ff3ed70db4739b3c6747c7f624fe2bad70802987
cp %{_builddir}/plasma-desktop-5.17.0/kcms/kfontinst/viewpart/COPYING.UNICODE %{buildroot}/usr/share/package-licenses/plasma-desktop/ae855f68ab20f57b2cc7e9b03f54a87563424eb9
cp %{_builddir}/plasma-desktop-5.17.0/kcms/touchpad/COPYING %{buildroot}/usr/share/package-licenses/plasma-desktop/8b24e55e650d5d13ae3b1a2162a70b5238400aed
cp %{_builddir}/plasma-desktop-5.17.0/solid-device-automounter/COPYING %{buildroot}/usr/share/package-licenses/plasma-desktop/7c203dee3a03037da436df03c4b25b659c073976
pushd clr-build
%make_install
popd
%find_lang kaccess
%find_lang kcm5_componentchooser
%find_lang kcm5_icons
%find_lang kcm5_joystick
%find_lang kcm5_kded
%find_lang kcm_colors
%find_lang kcm_cursortheme
%find_lang kcm_desktoppaths
%find_lang kcm_fonts
%find_lang kcm_launchfeedback
%find_lang kcmaccess
%find_lang kcmformats
%find_lang kcmkclock
%find_lang kcmkeyboard
%find_lang kcmkeys
%find_lang kcmmouse
%find_lang kcmsmserver
%find_lang kcmstyle
%find_lang kfontinst
%find_lang knetattach5
%find_lang krdb
%find_lang plasma_applet_org.kde.desktopcontainment
%find_lang attica_kde_plugin
%find_lang kcm5_baloofile
%find_lang kcm5_device_automounter
%find_lang kcm5_emoticons
%find_lang kcm_activities5
%find_lang kcm_autostart
%find_lang kcm_desktoptheme
%find_lang kcm_lookandfeel
%find_lang kcm_search
%find_lang kcm_solid_actions
%find_lang kcm_splashscreen
%find_lang kcm_standard_actions
%find_lang kcm_touchpad
%find_lang kcm_workspace
%find_lang plasma_applet_org.kde.kimpanel
%find_lang plasma_applet_org.kde.plasma.kicker
%find_lang plasma_applet_org.kde.plasma.kickoff
%find_lang plasma_applet_org.kde.plasma.minimizeall
%find_lang plasma_applet_org.kde.plasma.pager
%find_lang plasma_applet_org.kde.plasma.showActivityManager
%find_lang plasma_applet_org.kde.plasma.showdesktop
%find_lang plasma_applet_org.kde.plasma.taskmanager
%find_lang plasma_applet_org.kde.plasma.trash
%find_lang plasma_applet_org.kde.plasma.windowlist
%find_lang plasma_applet_touchpad
%find_lang plasma_runner_kwin
%find_lang plasma_runner_plasma-desktop
%find_lang plasma_shell_org.kde.plasma.desktop
%find_lang plasma_toolbox_org.kde.desktoptoolbox
%find_lang plasmaactivitymanager
%find_lang kcm_notifications
%find_lang plasma_applet_org.kde.panel
%find_lang kcm_nightcolor
%find_lang kcmqtquicksettings
%find_lang plasma_toolbox_org.kde.paneltoolbox

%files
%defattr(-,root,root,-)
/usr/lib64/kconf_update_bin/krdb_clearlibrarypath
/usr/lib64/libexec/kauth/fontinst
/usr/lib64/libexec/kauth/fontinst_helper
/usr/lib64/libexec/kauth/fontinst_x11
/usr/lib64/libexec/kauth/kcmdatetimehelper
/usr/lib64/libexec/kfontprint
/usr/lib64/libexec/kimpanel-ibus-panel
/usr/lib64/libexec/kimpanel-ibus-panel-launcher
/usr/lib64/libexec/plasma-changeicons

%files bin
%defattr(-,root,root,-)
/usr/bin/kaccess
/usr/bin/kapplymousetheme
/usr/bin/kcm-touchpad-list-devices
/usr/bin/kcolorschemeeditor
/usr/bin/kfontinst
/usr/bin/kfontview
/usr/bin/knetattach
/usr/bin/krdb
/usr/bin/lookandfeeltool
/usr/bin/solid-action-desktop-gen

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kcolorschemeeditor.desktop
/usr/share/applications/org.kde.kfontview.desktop
/usr/share/applications/org.kde.knetattach.desktop
/usr/share/config.kcfg/touchpad.kcfg
/usr/share/config.kcfg/touchpaddaemon.kcfg
/usr/share/dbus-1/interfaces/org.kde.touchpad.xml
/usr/share/dbus-1/services/org.kde.fontinst.service
/usr/share/dbus-1/system-services/org.kde.fontinst.service
/usr/share/dbus-1/system-services/org.kde.kcontrol.kcmclock.service
/usr/share/dbus-1/system.d/org.kde.fontinst.conf
/usr/share/dbus-1/system.d/org.kde.kcontrol.kcmclock.conf
/usr/share/icons/hicolor/128x128/devices/input-touchpad.png
/usr/share/icons/hicolor/128x128/mimetypes/fonts-package.png
/usr/share/icons/hicolor/16x16/apps/kfontview.png
/usr/share/icons/hicolor/16x16/devices/input-touchpad.png
/usr/share/icons/hicolor/16x16/mimetypes/fonts-package.png
/usr/share/icons/hicolor/22x22/apps/kfontview.png
/usr/share/icons/hicolor/22x22/devices/input-touchpad.png
/usr/share/icons/hicolor/22x22/mimetypes/fonts-package.png
/usr/share/icons/hicolor/24x24/devices/input-touchpad.png
/usr/share/icons/hicolor/256x256/devices/input-touchpad.png
/usr/share/icons/hicolor/32x32/apps/kfontview.png
/usr/share/icons/hicolor/32x32/devices/input-touchpad.png
/usr/share/icons/hicolor/32x32/mimetypes/fonts-package.png
/usr/share/icons/hicolor/48x48/apps/kfontview.png
/usr/share/icons/hicolor/48x48/devices/input-touchpad.png
/usr/share/icons/hicolor/48x48/mimetypes/fonts-package.png
/usr/share/icons/hicolor/64x64/apps/kfontview.png
/usr/share/icons/hicolor/64x64/devices/input-touchpad.png
/usr/share/icons/hicolor/64x64/mimetypes/fonts-package.png
/usr/share/icons/hicolor/96x96/devices/input-touchpad.png
/usr/share/icons/hicolor/scalable/apps/preferences-desktop-font-installer.svgz
/usr/share/icons/hicolor/scalable/devices/input-touchpad.svgz
/usr/share/kcm_componentchooser/kcm_browser.desktop
/usr/share/kcm_componentchooser/kcm_filemanager.desktop
/usr/share/kcm_componentchooser/kcm_kemail.desktop
/usr/share/kcm_componentchooser/kcm_terminal.desktop
/usr/share/kcmkeyboard/pics/epo.png
/usr/share/kcmkeys/kde3.kksrc
/usr/share/kcmkeys/kde4.kksrc
/usr/share/kcmkeys/mac4.kksrc
/usr/share/kcmkeys/unix3.kksrc
/usr/share/kcmkeys/win3.kksrc
/usr/share/kcmkeys/win4.kksrc
/usr/share/kcmkeys/wm3.kksrc
/usr/share/kcmmouse/cursor_large_black.pcf.gz
/usr/share/kcmmouse/cursor_large_white.pcf.gz
/usr/share/kcmmouse/cursor_small_white.pcf.gz
/usr/share/kcmmouse/pics/mouse_lh.png
/usr/share/kcmmouse/pics/mouse_rh.png
/usr/share/kcmsolidactions/solid-action-template.desktop
/usr/share/kconf_update/krdb_libpathwipe.upd
/usr/share/kcontrol/pics/logo.png
/usr/share/kcontrol/pics/mini-world.png
/usr/share/kdisplay/app-defaults/AAAAAAGeneral.ad
/usr/share/kdisplay/app-defaults/AAAMotif.ad
/usr/share/kdisplay/app-defaults/AAATk.ad
/usr/share/kdisplay/app-defaults/AAAXaw.ad
/usr/share/kdisplay/app-defaults/AcroRead.ad
/usr/share/kdisplay/app-defaults/Editres.ad
/usr/share/kdisplay/app-defaults/Emacs.ad
/usr/share/kdisplay/app-defaults/GV.ad
/usr/share/kdisplay/app-defaults/ML.ad
/usr/share/kdisplay/app-defaults/Nedit.ad
/usr/share/kdisplay/app-defaults/Netscape.ad
/usr/share/kdisplay/app-defaults/RVPlayer.ad
/usr/share/kdisplay/app-defaults/WPerfect.ad
/usr/share/kdisplay/app-defaults/XCalc.ad
/usr/share/kdisplay/app-defaults/XOsview.ad
/usr/share/kdisplay/app-defaults/XTerm.ad
/usr/share/kdisplay/app-defaults/XV.ad
/usr/share/kdisplay/app-defaults/Xawtv.ad
/usr/share/kdisplay/app-defaults/Xdvi.ad
/usr/share/kdisplay/app-defaults/Xpdf.ad
/usr/share/kf5/kactivitymanagerd/workspace/settings/qml/activitiesTab/ActivitiesView.qml
/usr/share/kf5/kactivitymanagerd/workspace/settings/qml/activitiesTab/main.qml
/usr/share/kf5/kactivitymanagerd/workspace/settings/qml/activityDialog/GeneralTab.qml
/usr/share/kf5/kactivitymanagerd/workspace/settings/qml/privacyTab/BlacklistApplicationView.qml
/usr/share/kfontinst/icons/hicolor/16x16/actions/addfont.png
/usr/share/kfontinst/icons/hicolor/16x16/actions/font-disable.png
/usr/share/kfontinst/icons/hicolor/16x16/actions/font-enable.png
/usr/share/kfontinst/icons/hicolor/16x16/actions/fontstatus.png
/usr/share/kfontinst/icons/hicolor/22x22/actions/addfont.png
/usr/share/kfontinst/icons/hicolor/22x22/actions/font-disable.png
/usr/share/kfontinst/icons/hicolor/22x22/actions/font-enable.png
/usr/share/kfontinst/icons/hicolor/22x22/actions/fontstatus.png
/usr/share/knotifications5/kaccess.notifyrc
/usr/share/knotifications5/kcm_touchpad.notifyrc
/usr/share/knsrcfiles/colorschemes.knsrc
/usr/share/knsrcfiles/emoticons.knsrc
/usr/share/knsrcfiles/icons.knsrc
/usr/share/knsrcfiles/kfontinst.knsrc
/usr/share/knsrcfiles/ksplash.knsrc
/usr/share/knsrcfiles/lookandfeel.knsrc
/usr/share/knsrcfiles/plasma-themes.knsrc
/usr/share/knsrcfiles/xcursor.knsrc
/usr/share/konqsidebartng/virtual_folders/services/fonts.desktop
/usr/share/kpackage/kcms/kcm5_icons/contents/ui/IconSizePopup.qml
/usr/share/kpackage/kcms/kcm5_icons/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm5_icons/metadata.desktop
/usr/share/kpackage/kcms/kcm5_icons/metadata.json
/usr/share/kpackage/kcms/kcm_colors/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_colors/metadata.desktop
/usr/share/kpackage/kcms/kcm_colors/metadata.json
/usr/share/kpackage/kcms/kcm_cursortheme/contents/ui/Delegate.qml
/usr/share/kpackage/kcms/kcm_cursortheme/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_cursortheme/metadata.desktop
/usr/share/kpackage/kcms/kcm_cursortheme/metadata.json
/usr/share/kpackage/kcms/kcm_desktoptheme/contents/ui/Hand.qml
/usr/share/kpackage/kcms/kcm_desktoptheme/contents/ui/ThemePreview.qml
/usr/share/kpackage/kcms/kcm_desktoptheme/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_desktoptheme/metadata.desktop
/usr/share/kpackage/kcms/kcm_desktoptheme/metadata.json
/usr/share/kpackage/kcms/kcm_fonts/contents/ui/FontWidget.qml
/usr/share/kpackage/kcms/kcm_fonts/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_fonts/metadata.desktop
/usr/share/kpackage/kcms/kcm_fonts/metadata.json
/usr/share/kpackage/kcms/kcm_launchfeedback/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_launchfeedback/metadata.desktop
/usr/share/kpackage/kcms/kcm_launchfeedback/metadata.json
/usr/share/kpackage/kcms/kcm_lookandfeel/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_lookandfeel/metadata.desktop
/usr/share/kpackage/kcms/kcm_lookandfeel/metadata.json
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/LocationsAutoView.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/LocationsFixedView.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/NumberField.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/TimeField.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/TimingsView.qml
/usr/share/kpackage/kcms/kcm_nightcolor/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_nightcolor/metadata.desktop
/usr/share/kpackage/kcms/kcm_nightcolor/metadata.json
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/ApplicationConfiguration.qml
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/PopupPositionPage.qml
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/ScreenPositionSelector.qml
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/SourcesPage.qml
/usr/share/kpackage/kcms/kcm_notifications/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_notifications/metadata.desktop
/usr/share/kpackage/kcms/kcm_notifications/metadata.json
/usr/share/kpackage/kcms/kcm_splashscreen/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_splashscreen/metadata.desktop
/usr/share/kpackage/kcms/kcm_splashscreen/metadata.json
/usr/share/kpackage/kcms/kcm_workspace/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_workspace/metadata.desktop
/usr/share/kpackage/kcms/kcm_workspace/metadata.json
/usr/share/kservices5/ServiceMenus/installfont.desktop
/usr/share/kservices5/autostart.desktop
/usr/share/kservices5/clock.desktop
/usr/share/kservices5/componentchooser.desktop
/usr/share/kservices5/desktoppath.desktop
/usr/share/kservices5/device_automounter_kcm.desktop
/usr/share/kservices5/emoticons.desktop
/usr/share/kservices5/fontinst.desktop
/usr/share/kservices5/fonts.protocol
/usr/share/kservices5/fontthumbnail.desktop
/usr/share/kservices5/formats.desktop
/usr/share/kservices5/joystick.desktop
/usr/share/kservices5/kaccess.desktop
/usr/share/kservices5/kcm_activities.desktop
/usr/share/kservices5/kcm_baloofile.desktop
/usr/share/kservices5/kcm_colors.desktop
/usr/share/kservices5/kcm_cursortheme.desktop
/usr/share/kservices5/kcm_desktoptheme.desktop
/usr/share/kservices5/kcm_fonts.desktop
/usr/share/kservices5/kcm_icons.desktop
/usr/share/kservices5/kcm_keyboard.desktop
/usr/share/kservices5/kcm_launchfeedback.desktop
/usr/share/kservices5/kcm_lookandfeel.desktop
/usr/share/kservices5/kcm_nightcolor.desktop
/usr/share/kservices5/kcm_notifications.desktop
/usr/share/kservices5/kcm_plasmasearch.desktop
/usr/share/kservices5/kcm_splashscreen.desktop
/usr/share/kservices5/kcm_touchpad.desktop
/usr/share/kservices5/kcm_workspace.desktop
/usr/share/kservices5/kcmaccess.desktop
/usr/share/kservices5/kcmkded.desktop
/usr/share/kservices5/kcmsmserver.desktop
/usr/share/kservices5/kded/touchpad.desktop
/usr/share/kservices5/keys.desktop
/usr/share/kservices5/kfontviewpart.desktop
/usr/share/kservices5/mouse.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.icontasks.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.kicker.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.kickoff.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.kimpanel.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.minimizeall.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.pager.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.showActivityManager.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.showdesktop.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.taskmanager.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.trash.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.windowlist.desktop
/usr/share/kservices5/plasma-applet-touchpad.desktop
/usr/share/kservices5/plasma-containment-org.kde.desktopcontainment.desktop
/usr/share/kservices5/plasma-containment-org.kde.panel.desktop
/usr/share/kservices5/plasma-containment-org.kde.plasma.folder.desktop
/usr/share/kservices5/plasma-dataengine-kimpanel.desktop
/usr/share/kservices5/plasma-dataengine-touchpad.desktop
/usr/share/kservices5/plasma-layout-template-org.kde.plasma.desktop.appmenubar.desktop
/usr/share/kservices5/plasma-layout-template-org.kde.plasma.desktop.defaultPanel.desktop
/usr/share/kservices5/plasma-layout-template-org.kde.plasma.desktop.emptyPanel.desktop
/usr/share/kservices5/plasma-package-org.kde.desktoptoolbox.desktop
/usr/share/kservices5/plasma-package-org.kde.paneltoolbox.desktop
/usr/share/kservices5/plasma-runner-kwin.desktop
/usr/share/kservices5/plasma-runner-plasma-desktop.desktop
/usr/share/kservices5/plasma-shell-org.kde.plasma.desktop.desktop
/usr/share/kservices5/qtquicksettings.desktop
/usr/share/kservices5/solid-actions.desktop
/usr/share/kservices5/spellchecking.desktop
/usr/share/kservices5/standard_actions.desktop
/usr/share/kservices5/style.desktop
/usr/share/kservicetypes5/solid-device-type.desktop
/usr/share/kxmlgui5/kfontinst/kfontviewpart.rc
/usr/share/kxmlgui5/kfontview/kfontviewui.rc
/usr/share/locale/sr/LC_SCRIPTS/kfontinst/kfontinst.js
/usr/share/locale/sr@ijekavian/LC_SCRIPTS/kfontinst/kfontinst.js
/usr/share/locale/sr@ijekavianlatin/LC_SCRIPTS/kfontinst/kfontinst.js
/usr/share/locale/sr@latin/LC_SCRIPTS/kfontinst/kfontinst.js
/usr/share/metainfo/org.kde.desktopcontainment.appdata.xml
/usr/share/metainfo/org.kde.desktoptoolbox.appdata.xml
/usr/share/metainfo/org.kde.paneltoolbox.appdata.xml
/usr/share/metainfo/org.kde.plasma.desktop.appdata.xml
/usr/share/metainfo/org.kde.plasma.desktop.appmenubar.appdata.xml
/usr/share/metainfo/org.kde.plasma.desktop.defaultPanel.appdata.xml
/usr/share/metainfo/org.kde.plasma.desktop.emptyPanel.appdata.xml
/usr/share/metainfo/org.kde.plasma.folder.appdata.xml
/usr/share/metainfo/org.kde.plasma.icontasks.appdata.xml
/usr/share/metainfo/org.kde.plasma.kicker.appdata.xml
/usr/share/metainfo/org.kde.plasma.kickoff.appdata.xml
/usr/share/metainfo/org.kde.plasma.kimpanel.appdata.xml
/usr/share/metainfo/org.kde.plasma.minimizeall.appdata.xml
/usr/share/metainfo/org.kde.plasma.pager.appdata.xml
/usr/share/metainfo/org.kde.plasma.showActivityManager.appdata.xml
/usr/share/metainfo/org.kde.plasma.showdesktop.appdata.xml
/usr/share/metainfo/org.kde.plasma.taskmanager.appdata.xml
/usr/share/metainfo/org.kde.plasma.trash.appdata.xml
/usr/share/metainfo/org.kde.plasma.windowlist.appdata.xml
/usr/share/metainfo/org.kde.plasmashell.metainfo.xml
/usr/share/plasma/desktoptheme/default/icons/touchpad.svg
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.appmenubar/contents/layout.js
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.appmenubar/metadata.desktop
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.appmenubar/metadata.json
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/contents/layout.js
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/metadata.desktop
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/metadata.json
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.emptyPanel/contents/layout.js
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.emptyPanel/metadata.desktop
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.emptyPanel/metadata.json
/usr/share/plasma/packages/org.kde.desktoptoolbox/contents/config/main.xml
/usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxButton.qml
/usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxItem.qml
/usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxRoot.qml
/usr/share/plasma/packages/org.kde.desktoptoolbox/metadata.desktop
/usr/share/plasma/packages/org.kde.desktoptoolbox/metadata.json
/usr/share/plasma/packages/org.kde.paneltoolbox/contents/ui/main.qml
/usr/share/plasma/packages/org.kde.paneltoolbox/metadata.desktop
/usr/share/plasma/packages/org.kde.paneltoolbox/metadata.json
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ActionButton.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/BackButtonItem.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/BusyOverlay.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ConfigFilter.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ConfigIcons.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ConfigLocation.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ConfigOverlay.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ConfigTweaks.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemActionButton.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemPreviewPluginsDialog.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderView.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderViewDialog.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderViewDropArea.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderViewLayer.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/code/FolderTools.js
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/metadata.json
/usr/share/plasma/plasmoids/org.kde.panel/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.panel/contents/ui/ConfigOverlay.qml
/usr/share/plasma/plasmoids/org.kde.panel/contents/ui/LayoutManager.js
/usr/share/plasma/plasmoids/org.kde.panel/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.panel/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.panel/metadata.json
/usr/share/plasma/plasmoids/org.kde.panel/plasma-containment-panel.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.folder/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.folder/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.icontasks/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.icontasks/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ActionMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ConfigGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/DashboardRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/DashboardTabBar.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/DashboardTabButton.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemGridDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemGridView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemListDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemListDialog.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemListView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemMultiGridView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/MenuRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/RunnerResultsList.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/SideBarItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/SideBarSection.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/code/tools.js
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/ActionMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/ApplicationsView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/BaseView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Breadcrumb.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/ComputerView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/ConfigButtons.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/ConfigGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/FavoritesView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/FullRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Header.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Kickoff.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffButton.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffConfigurationButton.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffHighlight.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffListView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/LeaveView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/OftenUsedView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/RecentlyUsedView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/SearchView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/SectionDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/code/tools.js
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/ActionMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/CandidateHighlight.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/ConfigAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/ContextMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/InputPanel.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/StatusIcon.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.minimizeall/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.minimizeall/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.minimizeall/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.minimizeall/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.pager/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.pager/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.pager/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.pager/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.pager/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.pager/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.showActivityManager/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.showActivityManager/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.showActivityManager/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.showdesktop/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.showdesktop/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.showdesktop/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.showdesktop/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/AudioStream.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Badge.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ConfigAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ConfigBehavior.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ContextMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/GroupDialog.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/GroupExpanderOverlay.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/MouseHandler.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/PulseAudio.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/TaskBadgeOverlay.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/TaskList.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/TaskProgressOverlay.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ToolTipDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ToolTipInstance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ToolTipWindowMouseArea.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/code/layout.js
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/code/tools.js
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.trash/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.trash/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.trash/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.windowlist/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.windowlist/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.windowlist/metadata.json
/usr/share/plasma/plasmoids/touchpad/contents/ui/touchpad.qml
/usr/share/plasma/plasmoids/touchpad/metadata.desktop
/usr/share/plasma/plasmoids/touchpad/metadata.json
/usr/share/plasma/services/kimpanel.operations
/usr/share/plasma/services/touchpad.operations
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/InteractiveConsole.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/ActivityItem.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/ActivityList.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/ActivityManager.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/Heading.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/StoppedActivityItem.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/WindowPreview.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/static.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/applet/AppletError.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/applet/CompactApplet.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/applet/DefaultCompactRepresentation.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigCategoryDelegate.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentActions.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationKcmPage.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationShortcuts.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ContainmentConfiguration.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/MouseEventInputButton.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/PanelConfiguration.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/EdgeHandle.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/MoreSettingsMenu.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/Ruler.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/SizeHandle.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/SliderHandle.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/ToolBar.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/defaults
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletAlternatives.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/Tooltip.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/WidgetExplorer.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/layout.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/move_desktop_layout_config.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/obsolete_kickoffrc.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/metadata.desktop
/usr/share/plasma/shells/org.kde.plasma.desktop/metadata.json
/usr/share/polkit-1/actions/org.kde.fontinst.policy
/usr/share/polkit-1/actions/org.kde.kcontrol.kcmclock.policy
/usr/share/solid/devices/solid-device-Battery.desktop
/usr/share/solid/devices/solid-device-Block.desktop
/usr/share/solid/devices/solid-device-Camera.desktop
/usr/share/solid/devices/solid-device-OpticalDisc.desktop
/usr/share/solid/devices/solid-device-OpticalDrive.desktop
/usr/share/solid/devices/solid-device-PortableMediaPlayer.desktop
/usr/share/solid/devices/solid-device-Processor.desktop
/usr/share/solid/devices/solid-device-StorageAccess.desktop
/usr/share/solid/devices/solid-device-StorageDrive.desktop
/usr/share/solid/devices/solid-device-StorageVolume.desktop

%files dev
%defattr(-,root,root,-)
/usr/lib64/libkfontinst.so
/usr/lib64/libkfontinstui.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/ca/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/ca/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/clock/index.docbook
/usr/share/doc/HTML/ca/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/colors/index.docbook
/usr/share/doc/HTML/ca/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/ca/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/ca/kcontrol/desktopthemedetails/edit-delete.png
/usr/share/doc/HTML/ca/kcontrol/desktopthemedetails/edit-undo.png
/usr/share/doc/HTML/ca/kcontrol/desktopthemedetails/get-new-theme.png
/usr/share/doc/HTML/ca/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/ca/kcontrol/desktopthemedetails/main.png
/usr/share/doc/HTML/ca/kcontrol/emoticons/emoticons.png
/usr/share/doc/HTML/ca/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/ca/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/ca/kcontrol/fonts/adjust-all.png
/usr/share/doc/HTML/ca/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/ca/kcontrol/fonts/main.png
/usr/share/doc/HTML/ca/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/formats/index.docbook
/usr/share/doc/HTML/ca/kcontrol/icons/edit-delete.png
/usr/share/doc/HTML/ca/kcontrol/icons/edit-undo.png
/usr/share/doc/HTML/ca/kcontrol/icons/get-new-theme.png
/usr/share/doc/HTML/ca/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/icons/index.docbook
/usr/share/doc/HTML/ca/kcontrol/icons/main.png
/usr/share/doc/HTML/ca/kcontrol/icons/use-of-icons.png
/usr/share/doc/HTML/ca/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kded/index.docbook
/usr/share/doc/HTML/ca/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/ca/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/keys/index.docbook
/usr/share/doc/HTML/ca/kcontrol/keys/list-add.png
/usr/share/doc/HTML/ca/kcontrol/keys/remove.png
/usr/share/doc/HTML/ca/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/ca/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/paths/index.docbook
/usr/share/doc/HTML/ca/kcontrol/paths/paths.png
/usr/share/doc/HTML/ca/kcontrol/solid-actions/add-action.png
/usr/share/doc/HTML/ca/kcontrol/solid-actions/edit-action.png
/usr/share/doc/HTML/ca/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/ca/kcontrol/solid-actions/main.png
/usr/share/doc/HTML/ca/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/ca/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/ca/kcontrol/splashscreen/get-new-theme.png
/usr/share/doc/HTML/ca/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/ca/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/ca/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/ca/kfontview/index.cache.bz2
/usr/share/doc/HTML/ca/kfontview/index.docbook
/usr/share/doc/HTML/ca/kfontview/kfontview.png
/usr/share/doc/HTML/ca/knetattach/index.cache.bz2
/usr/share/doc/HTML/ca/knetattach/index.docbook
/usr/share/doc/HTML/ca/knetattach/screenshot.png
/usr/share/doc/HTML/ca/knetattach/screenshot1.png
/usr/share/doc/HTML/ca/knetattach/screenshot2.png
/usr/share/doc/HTML/ca/knetattach/screenshot3.png
/usr/share/doc/HTML/ca/knetattach/screenshot4.png
/usr/share/doc/HTML/ca/plasma-desktop/add-widgets.png
/usr/share/doc/HTML/ca/plasma-desktop/application-launcher-settings.png
/usr/share/doc/HTML/ca/plasma-desktop/application-launcher.png
/usr/share/doc/HTML/ca/plasma-desktop/application-menu.png
/usr/share/doc/HTML/ca/plasma-desktop/device_notifier_widget.png
/usr/share/doc/HTML/ca/plasma-desktop/device_notifier_widget_actions.png
/usr/share/doc/HTML/ca/plasma-desktop/folder-view.png
/usr/share/doc/HTML/ca/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/ca/plasma-desktop/index.docbook
/usr/share/doc/HTML/ca/plasma-desktop/krunner-configure.png
/usr/share/doc/HTML/ca/plasma-desktop/krunner-desktop-actions.png
/usr/share/doc/HTML/ca/plasma-desktop/plasma-desktop-annotated.png
/usr/share/doc/HTML/ca/plasma-desktop/remove.png
/usr/share/doc/HTML/ca/plasma-desktop/system-tray-up-arrow.png
/usr/share/doc/HTML/de/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/de/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/de/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/clock/index.docbook
/usr/share/doc/HTML/de/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/colors/index.docbook
/usr/share/doc/HTML/de/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/de/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/de/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/de/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/de/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/de/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/de/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/formats/index.docbook
/usr/share/doc/HTML/de/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/icons/index.docbook
/usr/share/doc/HTML/de/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/de/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kded/index.docbook
/usr/share/doc/HTML/de/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/de/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/keys/index.docbook
/usr/share/doc/HTML/de/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/de/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/paths/index.docbook
/usr/share/doc/HTML/de/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/de/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/de/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/de/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/de/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/de/kfontview/index.cache.bz2
/usr/share/doc/HTML/de/kfontview/index.docbook
/usr/share/doc/HTML/de/knetattach/index.cache.bz2
/usr/share/doc/HTML/de/knetattach/index.docbook
/usr/share/doc/HTML/de/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/de/plasma-desktop/index.docbook
/usr/share/doc/HTML/en/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/en/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/en/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/clock/index.docbook
/usr/share/doc/HTML/en/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/colors/index.docbook
/usr/share/doc/HTML/en/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/en/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/edit-delete.png
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/edit-undo.png
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/get-new-theme.png
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/en/kcontrol/desktopthemedetails/main.png
/usr/share/doc/HTML/en/kcontrol/emoticons/emoticons.png
/usr/share/doc/HTML/en/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/en/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/en/kcontrol/fonts/adjust-all.png
/usr/share/doc/HTML/en/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/en/kcontrol/fonts/main.png
/usr/share/doc/HTML/en/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/formats/index.docbook
/usr/share/doc/HTML/en/kcontrol/icons/edit-delete.png
/usr/share/doc/HTML/en/kcontrol/icons/edit-undo.png
/usr/share/doc/HTML/en/kcontrol/icons/get-new-theme.png
/usr/share/doc/HTML/en/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/icons/index.docbook
/usr/share/doc/HTML/en/kcontrol/icons/main.png
/usr/share/doc/HTML/en/kcontrol/icons/use-of-icons.png
/usr/share/doc/HTML/en/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/en/kcontrol/joystick/joystick-calibration.png
/usr/share/doc/HTML/en/kcontrol/joystick/joystick-main.png
/usr/share/doc/HTML/en/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/en/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/en/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/en/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/en/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/en/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kded/index.docbook
/usr/share/doc/HTML/en/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/en/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/keys/index.docbook
/usr/share/doc/HTML/en/kcontrol/keys/list-add.png
/usr/share/doc/HTML/en/kcontrol/keys/remove.png
/usr/share/doc/HTML/en/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/en/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/paths/index.docbook
/usr/share/doc/HTML/en/kcontrol/paths/paths.png
/usr/share/doc/HTML/en/kcontrol/solid-actions/add-action.png
/usr/share/doc/HTML/en/kcontrol/solid-actions/edit-action.png
/usr/share/doc/HTML/en/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/en/kcontrol/solid-actions/main.png
/usr/share/doc/HTML/en/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/en/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/en/kcontrol/splashscreen/get-new-theme.png
/usr/share/doc/HTML/en/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/en/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/en/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/en/kfontview/index.cache.bz2
/usr/share/doc/HTML/en/kfontview/index.docbook
/usr/share/doc/HTML/en/kfontview/kfontview.png
/usr/share/doc/HTML/en/knetattach/index.cache.bz2
/usr/share/doc/HTML/en/knetattach/index.docbook
/usr/share/doc/HTML/en/knetattach/screenshot.png
/usr/share/doc/HTML/en/knetattach/screenshot1.png
/usr/share/doc/HTML/en/knetattach/screenshot2.png
/usr/share/doc/HTML/en/knetattach/screenshot3.png
/usr/share/doc/HTML/en/knetattach/screenshot4.png
/usr/share/doc/HTML/en/plasma-desktop/add-widgets.png
/usr/share/doc/HTML/en/plasma-desktop/application-launcher-settings.png
/usr/share/doc/HTML/en/plasma-desktop/application-launcher.png
/usr/share/doc/HTML/en/plasma-desktop/application-menu.png
/usr/share/doc/HTML/en/plasma-desktop/desktop-settings.png
/usr/share/doc/HTML/en/plasma-desktop/device_notifier_widget.png
/usr/share/doc/HTML/en/plasma-desktop/device_notifier_widget_actions.png
/usr/share/doc/HTML/en/plasma-desktop/folder-view.png
/usr/share/doc/HTML/en/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/en/plasma-desktop/index.docbook
/usr/share/doc/HTML/en/plasma-desktop/krunner-configure.png
/usr/share/doc/HTML/en/plasma-desktop/krunner-desktop-actions.png
/usr/share/doc/HTML/en/plasma-desktop/krunner.png
/usr/share/doc/HTML/en/plasma-desktop/panel-settings.png
/usr/share/doc/HTML/en/plasma-desktop/plasma-desktop-annotated.png
/usr/share/doc/HTML/en/plasma-desktop/remove.png
/usr/share/doc/HTML/en/plasma-desktop/system-tray-settings.png
/usr/share/doc/HTML/en/plasma-desktop/system-tray-up-arrow.png
/usr/share/doc/HTML/en/plasma-desktop/taskbar-settings.png
/usr/share/doc/HTML/es/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/es/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/es/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/clock/index.docbook
/usr/share/doc/HTML/es/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/es/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/es/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/es/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/es/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/es/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/es/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/es/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/es/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/es/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/es/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/es/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kded/index.docbook
/usr/share/doc/HTML/es/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/es/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/paths/index.docbook
/usr/share/doc/HTML/es/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/es/kfontview/index.cache.bz2
/usr/share/doc/HTML/es/kfontview/index.docbook
/usr/share/doc/HTML/es/knetattach/index.cache.bz2
/usr/share/doc/HTML/es/knetattach/index.docbook
/usr/share/doc/HTML/et/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/clock/index.docbook
/usr/share/doc/HTML/et/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/et/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/id/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/id/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/id/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/clock/index.docbook
/usr/share/doc/HTML/id/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/colors/index.docbook
/usr/share/doc/HTML/id/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/id/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/id/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/id/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/id/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/id/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/id/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/formats/index.docbook
/usr/share/doc/HTML/id/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/icons/index.docbook
/usr/share/doc/HTML/id/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/id/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/id/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/id/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/id/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/id/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/id/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kded/index.docbook
/usr/share/doc/HTML/id/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/id/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/keys/index.docbook
/usr/share/doc/HTML/id/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/id/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/paths/index.docbook
/usr/share/doc/HTML/id/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/id/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/id/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/id/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/id/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/id/kfontview/index.cache.bz2
/usr/share/doc/HTML/id/kfontview/index.docbook
/usr/share/doc/HTML/id/knetattach/index.cache.bz2
/usr/share/doc/HTML/id/knetattach/index.docbook
/usr/share/doc/HTML/id/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/id/plasma-desktop/index.docbook
/usr/share/doc/HTML/it/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/it/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/it/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/clock/index.docbook
/usr/share/doc/HTML/it/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/colors/index.docbook
/usr/share/doc/HTML/it/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/it/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/it/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/it/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/it/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/it/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/it/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/formats/index.docbook
/usr/share/doc/HTML/it/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/icons/index.docbook
/usr/share/doc/HTML/it/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/it/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kded/index.docbook
/usr/share/doc/HTML/it/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/it/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/keys/index.docbook
/usr/share/doc/HTML/it/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/it/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/paths/index.docbook
/usr/share/doc/HTML/it/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/it/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/it/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/it/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/it/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/it/kfontview/index.cache.bz2
/usr/share/doc/HTML/it/kfontview/index.docbook
/usr/share/doc/HTML/it/knetattach/index.cache.bz2
/usr/share/doc/HTML/it/knetattach/index.docbook
/usr/share/doc/HTML/it/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/it/plasma-desktop/index.docbook
/usr/share/doc/HTML/nl/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/nl/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/nl/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/clock/index.docbook
/usr/share/doc/HTML/nl/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/colors/index.docbook
/usr/share/doc/HTML/nl/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/nl/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/nl/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/nl/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/nl/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/nl/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/nl/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/formats/index.docbook
/usr/share/doc/HTML/nl/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/icons/index.docbook
/usr/share/doc/HTML/nl/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kded/index.docbook
/usr/share/doc/HTML/nl/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/nl/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/keys/index.docbook
/usr/share/doc/HTML/nl/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/nl/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/paths/index.docbook
/usr/share/doc/HTML/nl/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/nl/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/nl/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/nl/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/nl/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/nl/kfontview/index.cache.bz2
/usr/share/doc/HTML/nl/kfontview/index.docbook
/usr/share/doc/HTML/nl/knetattach/index.cache.bz2
/usr/share/doc/HTML/nl/knetattach/index.docbook
/usr/share/doc/HTML/nl/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/nl/plasma-desktop/index.docbook
/usr/share/doc/HTML/pt/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/pt/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/pt/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/clock/index.docbook
/usr/share/doc/HTML/pt/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/colors/index.docbook
/usr/share/doc/HTML/pt/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/pt/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/pt/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/pt/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/pt/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/pt/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/pt/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/formats/index.docbook
/usr/share/doc/HTML/pt/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kded/index.docbook
/usr/share/doc/HTML/pt/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/pt/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/keys/index.docbook
/usr/share/doc/HTML/pt/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/pt/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/paths/index.docbook
/usr/share/doc/HTML/pt/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/pt/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/pt/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/pt/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/pt/kfontview/index.cache.bz2
/usr/share/doc/HTML/pt/kfontview/index.docbook
/usr/share/doc/HTML/pt/knetattach/index.cache.bz2
/usr/share/doc/HTML/pt/knetattach/index.docbook
/usr/share/doc/HTML/pt/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/pt/plasma-desktop/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/clock/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/colors/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/desktopthemedetails/customizing.png
/usr/share/doc/HTML/pt_BR/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/emoticons/emoticons.png
/usr/share/doc/HTML/pt_BR/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/fonts/adjust-all.png
/usr/share/doc/HTML/pt_BR/kcontrol/fonts/anti-aliasing.png
/usr/share/doc/HTML/pt_BR/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/fonts/main.png
/usr/share/doc/HTML/pt_BR/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/formats/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/icons/effects.png
/usr/share/doc/HTML/pt_BR/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/icons/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/icons/install-theme.png
/usr/share/doc/HTML/pt_BR/kcontrol/icons/main.png
/usr/share/doc/HTML/pt_BR/kcontrol/icons/use-of-icons.png
/usr/share/doc/HTML/pt_BR/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kded/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/keys/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/paths/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/pt_BR/kfontview/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kfontview/index.docbook
/usr/share/doc/HTML/pt_BR/knetattach/index.cache.bz2
/usr/share/doc/HTML/pt_BR/knetattach/index.docbook
/usr/share/doc/HTML/pt_BR/knetattach/screenshot.png
/usr/share/doc/HTML/pt_BR/knetattach/screenshot1.png
/usr/share/doc/HTML/pt_BR/knetattach/screenshot2.png
/usr/share/doc/HTML/pt_BR/knetattach/screenshot3.png
/usr/share/doc/HTML/pt_BR/knetattach/screenshot4.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/add-widgets.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/desktop-settings.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/pt_BR/plasma-desktop/index.docbook
/usr/share/doc/HTML/pt_BR/plasma-desktop/krunner-configure.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/krunner.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/panel-settings.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/system-tray-settings.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/system-tray-up-arrow.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/taskbar-settings.png
/usr/share/doc/HTML/ru/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/ru/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/clock/index.docbook
/usr/share/doc/HTML/ru/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/colors/index.docbook
/usr/share/doc/HTML/ru/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/ru/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/ru/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/ru/kcontrol/emoticons/emoticons.png
/usr/share/doc/HTML/ru/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/ru/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/ru/kcontrol/fonts/adjust-all.png
/usr/share/doc/HTML/ru/kcontrol/fonts/anti-aliasing.png
/usr/share/doc/HTML/ru/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/ru/kcontrol/fonts/main.png
/usr/share/doc/HTML/ru/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/formats/index.docbook
/usr/share/doc/HTML/ru/kcontrol/icons/delete-theme.png
/usr/share/doc/HTML/ru/kcontrol/icons/effects.png
/usr/share/doc/HTML/ru/kcontrol/icons/get-new-theme.png
/usr/share/doc/HTML/ru/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/icons/index.docbook
/usr/share/doc/HTML/ru/kcontrol/icons/install-theme.png
/usr/share/doc/HTML/ru/kcontrol/icons/main.png
/usr/share/doc/HTML/ru/kcontrol/icons/size.png
/usr/share/doc/HTML/ru/kcontrol/icons/use-of-icons.png
/usr/share/doc/HTML/ru/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/ru/kcontrol/joystick/joystick-calibration.png
/usr/share/doc/HTML/ru/kcontrol/joystick/joystick-main.png
/usr/share/doc/HTML/ru/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kded/index.docbook
/usr/share/doc/HTML/ru/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/ru/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/keys/index.docbook
/usr/share/doc/HTML/ru/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/ru/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/paths/index.docbook
/usr/share/doc/HTML/ru/kcontrol/paths/paths.png
/usr/share/doc/HTML/ru/kcontrol/solid-actions/add-action.png
/usr/share/doc/HTML/ru/kcontrol/solid-actions/edit-action.png
/usr/share/doc/HTML/ru/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/ru/kcontrol/solid-actions/main.png
/usr/share/doc/HTML/ru/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/ru/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/ru/kcontrol/splashscreen/get-new-theme.png
/usr/share/doc/HTML/ru/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/ru/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/ru/knetattach/index.cache.bz2
/usr/share/doc/HTML/ru/knetattach/index.docbook
/usr/share/doc/HTML/ru/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/ru/plasma-desktop/index.docbook
/usr/share/doc/HTML/sr/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/sr/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/clock/index.docbook
/usr/share/doc/HTML/sr/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/sr/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/icons/index.docbook
/usr/share/doc/HTML/sr/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/sr/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/sr/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/paths/index.docbook
/usr/share/doc/HTML/sr/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/sr/knetattach/index.cache.bz2
/usr/share/doc/HTML/sr/knetattach/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/clock/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/icons/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/paths/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/sr@latin/knetattach/index.cache.bz2
/usr/share/doc/HTML/sr@latin/knetattach/index.docbook
/usr/share/doc/HTML/sv/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/sv/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/sv/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/clock/index.docbook
/usr/share/doc/HTML/sv/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/colors/index.docbook
/usr/share/doc/HTML/sv/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/sv/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/sv/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/sv/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/sv/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/sv/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/sv/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/formats/index.docbook
/usr/share/doc/HTML/sv/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/icons/index.docbook
/usr/share/doc/HTML/sv/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kded/index.docbook
/usr/share/doc/HTML/sv/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/sv/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/keys/index.docbook
/usr/share/doc/HTML/sv/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/sv/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/paths/index.docbook
/usr/share/doc/HTML/sv/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/sv/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/sv/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/sv/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/sv/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/sv/kfontview/index.cache.bz2
/usr/share/doc/HTML/sv/kfontview/index.docbook
/usr/share/doc/HTML/sv/knetattach/index.cache.bz2
/usr/share/doc/HTML/sv/knetattach/index.docbook
/usr/share/doc/HTML/sv/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/sv/plasma-desktop/index.docbook
/usr/share/doc/HTML/uk/kcontrol/autostart/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/autostart/index.docbook
/usr/share/doc/HTML/uk/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/uk/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/clock/index.docbook
/usr/share/doc/HTML/uk/kcontrol/colors/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/colors/index.docbook
/usr/share/doc/HTML/uk/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/uk/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/uk/kcontrol/desktopthemedetails/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/desktopthemedetails/index.docbook
/usr/share/doc/HTML/uk/kcontrol/emoticons/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/emoticons/index.docbook
/usr/share/doc/HTML/uk/kcontrol/fontinst/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/fontinst/index.docbook
/usr/share/doc/HTML/uk/kcontrol/fonts/adjust-all.png
/usr/share/doc/HTML/uk/kcontrol/fonts/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/fonts/index.docbook
/usr/share/doc/HTML/uk/kcontrol/formats/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/formats/index.docbook
/usr/share/doc/HTML/uk/kcontrol/icons/get-new-theme.png
/usr/share/doc/HTML/uk/kcontrol/icons/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/icons/index.docbook
/usr/share/doc/HTML/uk/kcontrol/icons/main.png
/usr/share/doc/HTML/uk/kcontrol/icons/use-of-icons.png
/usr/share/doc/HTML/uk/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmnotify/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmnotify/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmstyle/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmstyle/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kded/index.docbook
/usr/share/doc/HTML/uk/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/uk/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/keys/index.docbook
/usr/share/doc/HTML/uk/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/uk/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/paths/index.docbook
/usr/share/doc/HTML/uk/kcontrol/paths/paths.png
/usr/share/doc/HTML/uk/kcontrol/solid-actions/add-action.png
/usr/share/doc/HTML/uk/kcontrol/solid-actions/edit-action.png
/usr/share/doc/HTML/uk/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/uk/kcontrol/solid-actions/main.png
/usr/share/doc/HTML/uk/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/uk/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/uk/kcontrol/splashscreen/get-new-theme.png
/usr/share/doc/HTML/uk/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/uk/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/uk/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/uk/kfontview/index.cache.bz2
/usr/share/doc/HTML/uk/kfontview/index.docbook
/usr/share/doc/HTML/uk/kfontview/kfontview.png
/usr/share/doc/HTML/uk/knetattach/index.cache.bz2
/usr/share/doc/HTML/uk/knetattach/index.docbook
/usr/share/doc/HTML/uk/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/uk/plasma-desktop/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/libkdeinit5_kaccess.so
/usr/lib64/libkfontinst.so.5
/usr/lib64/libkfontinst.so.5.17.0
/usr/lib64/libkfontinstui.so.5
/usr/lib64/libkfontinstui.so.5.17.0
/usr/lib64/qt5/plugins/attica_kde.so
/usr/lib64/qt5/plugins/fontthumbnail.so
/usr/lib64/qt5/plugins/kcm_access.so
/usr/lib64/qt5/plugins/kcm_activities.so
/usr/lib64/qt5/plugins/kcm_autostart.so
/usr/lib64/qt5/plugins/kcm_baloofile.so
/usr/lib64/qt5/plugins/kcm_clock.so
/usr/lib64/qt5/plugins/kcm_componentchooser.so
/usr/lib64/qt5/plugins/kcm_desktoppaths.so
/usr/lib64/qt5/plugins/kcm_emoticons.so
/usr/lib64/qt5/plugins/kcm_fontinst.so
/usr/lib64/qt5/plugins/kcm_formats.so
/usr/lib64/qt5/plugins/kcm_joystick.so
/usr/lib64/qt5/plugins/kcm_kded.so
/usr/lib64/qt5/plugins/kcm_keyboard.so
/usr/lib64/qt5/plugins/kcm_keys.so
/usr/lib64/qt5/plugins/kcm_mouse.so
/usr/lib64/qt5/plugins/kcm_plasmasearch.so
/usr/lib64/qt5/plugins/kcm_smserver.so
/usr/lib64/qt5/plugins/kcm_solid_actions.so
/usr/lib64/qt5/plugins/kcm_standard_actions.so
/usr/lib64/qt5/plugins/kcm_style.so
/usr/lib64/qt5/plugins/kcms/kcm_colors.so
/usr/lib64/qt5/plugins/kcms/kcm_cursortheme.so
/usr/lib64/qt5/plugins/kcms/kcm_desktoptheme.so
/usr/lib64/qt5/plugins/kcms/kcm_fonts.so
/usr/lib64/qt5/plugins/kcms/kcm_icons.so
/usr/lib64/qt5/plugins/kcms/kcm_launchfeedback.so
/usr/lib64/qt5/plugins/kcms/kcm_lookandfeel.so
/usr/lib64/qt5/plugins/kcms/kcm_nightcolor.so
/usr/lib64/qt5/plugins/kcms/kcm_notifications.so
/usr/lib64/qt5/plugins/kcms/kcm_splashscreen.so
/usr/lib64/qt5/plugins/kcms/kcm_workspace.so
/usr/lib64/qt5/plugins/kcmspellchecking.so
/usr/lib64/qt5/plugins/kded_touchpad.so
/usr/lib64/qt5/plugins/kf5/kded/device_automounter.so
/usr/lib64/qt5/plugins/kf5/kded/keyboard.so
/usr/lib64/qt5/plugins/kfontviewpart.so
/usr/lib64/qt5/plugins/kio_fonts.so
/usr/lib64/qt5/plugins/krunner_kwin.so
/usr/lib64/qt5/plugins/krunner_plasma-desktop.so
/usr/lib64/qt5/plugins/libkcm_device_automounter.so
/usr/lib64/qt5/plugins/libkcm_qtquicksettings.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_kimpanel.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_touchpad.so
/usr/lib64/qt5/qml/org/kde/activities/settings/libkactivitiessettingsplugin.so
/usr/lib64/qt5/qml/org/kde/activities/settings/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/activityswitcher/libactivityswitcherextensionplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/activityswitcher/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/kimpanel/libkimpanelplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/kimpanel/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/pager/libpagerplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/pager/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/showdesktop/libshowdesktopplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/showdesktop/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/taskmanager/libtaskmanagerplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/taskmanager/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/trash/libtrashplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/trash/qmldir
/usr/lib64/qt5/qml/org/kde/private/desktopcontainment/desktop/libdesktopplugin.so
/usr/lib64/qt5/qml/org/kde/private/desktopcontainment/desktop/qmldir
/usr/lib64/qt5/qml/org/kde/private/desktopcontainment/folder/libfolderplugin.so
/usr/lib64/qt5/qml/org/kde/private/desktopcontainment/folder/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plasma-desktop/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/plasma-desktop/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/plasma-desktop/57c3cb6b9aee09ae2af06b0c517e2969d2f33d47
/usr/share/package-licenses/plasma-desktop/7c203dee3a03037da436df03c4b25b659c073976
/usr/share/package-licenses/plasma-desktop/8b24e55e650d5d13ae3b1a2162a70b5238400aed
/usr/share/package-licenses/plasma-desktop/9a1929f4700d2407c70b507b3b2aaf6226a9543c
/usr/share/package-licenses/plasma-desktop/ae855f68ab20f57b2cc7e9b03f54a87563424eb9
/usr/share/package-licenses/plasma-desktop/ba8966e2473a9969bdcab3dc82274c817cfd98a1
/usr/share/package-licenses/plasma-desktop/bd75d59f9d7d9731bfabdc48ecd19e704d218e38
/usr/share/package-licenses/plasma-desktop/ff3ed70db4739b3c6747c7f624fe2bad70802987

%files locales -f kaccess.lang -f kcm5_componentchooser.lang -f kcm5_icons.lang -f kcm5_joystick.lang -f kcm5_kded.lang -f kcm_colors.lang -f kcm_cursortheme.lang -f kcm_desktoppaths.lang -f kcm_fonts.lang -f kcm_launchfeedback.lang -f kcmaccess.lang -f kcmformats.lang -f kcmkclock.lang -f kcmkeyboard.lang -f kcmkeys.lang -f kcmmouse.lang -f kcmsmserver.lang -f kcmstyle.lang -f kfontinst.lang -f knetattach5.lang -f krdb.lang -f plasma_applet_org.kde.desktopcontainment.lang -f attica_kde_plugin.lang -f kcm5_baloofile.lang -f kcm5_device_automounter.lang -f kcm5_emoticons.lang -f kcm_activities5.lang -f kcm_autostart.lang -f kcm_desktoptheme.lang -f kcm_lookandfeel.lang -f kcm_search.lang -f kcm_solid_actions.lang -f kcm_splashscreen.lang -f kcm_standard_actions.lang -f kcm_touchpad.lang -f kcm_workspace.lang -f plasma_applet_org.kde.kimpanel.lang -f plasma_applet_org.kde.plasma.kicker.lang -f plasma_applet_org.kde.plasma.kickoff.lang -f plasma_applet_org.kde.plasma.minimizeall.lang -f plasma_applet_org.kde.plasma.pager.lang -f plasma_applet_org.kde.plasma.showActivityManager.lang -f plasma_applet_org.kde.plasma.showdesktop.lang -f plasma_applet_org.kde.plasma.taskmanager.lang -f plasma_applet_org.kde.plasma.trash.lang -f plasma_applet_org.kde.plasma.windowlist.lang -f plasma_applet_touchpad.lang -f plasma_runner_kwin.lang -f plasma_runner_plasma-desktop.lang -f plasma_shell_org.kde.plasma.desktop.lang -f plasma_toolbox_org.kde.desktoptoolbox.lang -f plasmaactivitymanager.lang -f kcm_notifications.lang -f plasma_applet_org.kde.panel.lang -f kcm_nightcolor.lang -f kcmqtquicksettings.lang -f plasma_toolbox_org.kde.paneltoolbox.lang
%defattr(-,root,root,-)

