#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : plasma-desktop
Version  : 5.25.5
Release  : 88
URL      : https://download.kde.org/stable/plasma/5.25.5/plasma-desktop-5.25.5.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.25.5/plasma-desktop-5.25.5.tar.xz
Source1  : https://download.kde.org/stable/plasma/5.25.5/plasma-desktop-5.25.5.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GFDL-1.2 GPL-2.0 GPL-3.0 HPND LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: plasma-desktop-bin = %{version}-%{release}
Requires: plasma-desktop-data = %{version}-%{release}
Requires: plasma-desktop-lib = %{version}-%{release}
Requires: plasma-desktop-license = %{version}-%{release}
Requires: plasma-desktop-locales = %{version}-%{release}
BuildRequires : baloo-dev
BuildRequires : boost-dev
BuildRequires : breeze-dev
BuildRequires : breeze-icons
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules pkgconfig(glib-2.0)
BuildRequires : extra-cmake-modules pkgconfig(x11-xcb)
BuildRequires : extra-cmake-modules pkgconfig(xcb) xcb-util-cursor-dev xcb-util-image-dev xcb-util-keysyms-dev xcb-util-renderutil-dev xcb-util-wm-dev xcb-util-dev
BuildRequires : extra-cmake-modules-data
BuildRequires : ibus-dev
BuildRequires : kaccounts-integration-dev
BuildRequires : kactivities-dev
BuildRequires : kactivities-stats-dev
BuildRequires : kcompletion-dev
BuildRequires : kcrash-dev
BuildRequires : kded-dev
BuildRequires : kdesignerplugin-dev
BuildRequires : kdoctools
BuildRequires : kdoctools-dev
BuildRequires : kemoticons-dev
BuildRequires : kfilemetadata-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kguiaddons-dev
BuildRequires : ki18n-dev
BuildRequires : kiconthemes-dev
BuildRequires : kinit-dev
BuildRequires : kirigami2-dev
BuildRequires : kitemmodels-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : knewstuff-dev
BuildRequires : knotifyconfig-dev
BuildRequires : kparts-dev
BuildRequires : krunner-dev
BuildRequires : kscreenlocker-dev
BuildRequires : ktextwidgets-dev
BuildRequires : kunitconversion-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kwin-dev
BuildRequires : kwindowsystem-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libXcursor-dev
BuildRequires : libXi-dev
BuildRequires : libevdev-dev
BuildRequires : libinput-dev
BuildRequires : libksysguard-dev
BuildRequires : libxcb-dev
BuildRequires : libxkbfile-dev
BuildRequires : phonon-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Concurrent)
BuildRequires : pkgconfig(Qt5DBus)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickWidgets)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5X11Extras)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xkeyboard-config)
BuildRequires : pkgconfig(xorg-evdev)
BuildRequires : pkgconfig(xorg-libinput)
BuildRequires : pkgconfig(xorg-server)
BuildRequires : pkgconfig(xorg-synaptics)
BuildRequires : plasma-framework-dev
BuildRequires : plasma-workspace-dev
BuildRequires : pulseaudio-dev
BuildRequires : qqc2-desktop-style-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtx11extras-dev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : systemd-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-image-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev
BuildRequires : xorg-server-dev

%description
This is new project to replace keyboard (kcmmisc) and kxkb
to manage keyboard hardware configuration and layouts.

%package bin
Summary: bin components for the plasma-desktop package.
Group: Binaries
Requires: plasma-desktop-data = %{version}-%{release}
Requires: plasma-desktop-license = %{version}-%{release}

%description bin
bin components for the plasma-desktop package.


%package data
Summary: data components for the plasma-desktop package.
Group: Data

%description data
data components for the plasma-desktop package.


%package doc
Summary: doc components for the plasma-desktop package.
Group: Documentation

%description doc
doc components for the plasma-desktop package.


%package lib
Summary: lib components for the plasma-desktop package.
Group: Libraries
Requires: plasma-desktop-data = %{version}-%{release}
Requires: plasma-desktop-license = %{version}-%{release}

%description lib
lib components for the plasma-desktop package.


%package license
Summary: license components for the plasma-desktop package.
Group: Default

%description license
license components for the plasma-desktop package.


%package locales
Summary: locales components for the plasma-desktop package.
Group: Default

%description locales
locales components for the plasma-desktop package.


%prep
%setup -q -n plasma-desktop-5.25.5
cd %{_builddir}/plasma-desktop-5.25.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1662508070
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1662508070
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plasma-desktop
cp %{_builddir}/plasma-desktop-%{version}/COPYING.DOC %{buildroot}/usr/share/package-licenses/plasma-desktop/bd75d59f9d7d9731bfabdc48ecd19e704d218e38 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/GFDL-1.2-or-later.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/ee03d68f6be20b170e5ea5d114d6acafb3f2d1dc || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/2123756e0b1fc8243547235a33c0fcabfe3b9a51 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/19d98e1b6f8ef12849ea4012a052d3907f336c91 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LicenseRef-synaptics.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/d08cb4fd7d3ab2539fc98f64d2c713453dfe46b5 || :
cp %{_builddir}/plasma-desktop-%{version}/LICENSES/LicenseRef-synaptics.txt %{buildroot}/usr/share/package-licenses/plasma-desktop/d08cb4fd7d3ab2539fc98f64d2c713453dfe46b5 || :
cp %{_builddir}/plasma-desktop-%{version}/applets/kimpanel/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/plasma-desktop/57c3cb6b9aee09ae2af06b0c517e2969d2f33d47 || :
pushd clr-build
%make_install
popd
%find_lang kaccess
%find_lang kcm5_joystick
%find_lang kcm5_kded
%find_lang kcm_access
%find_lang kcm_componentchooser
%find_lang kcm_desktoppaths
%find_lang kcm_launchfeedback
%find_lang kcm_smserver
%find_lang kcmkclock
%find_lang kcmkeyboard
%find_lang kcmmouse
%find_lang knetattach5
%find_lang plasma_applet_org.kde.desktopcontainment
%find_lang kcm5_device_automounter
%find_lang kcm_activities5
%find_lang kcm_baloofile
%find_lang kcm_keys
%find_lang kcm_krunnersettings
%find_lang kcm_landingpage
%find_lang kcm_search
%find_lang kcm_solid_actions
%find_lang kcm_splashscreen
%find_lang kcm_tablet
%find_lang kcm_touchpad
%find_lang kcm_workspace
%find_lang kcmqtquicksettings
%find_lang org.kde.plasma.emojier
%find_lang plasma_applet_org.kde.panel
%find_lang plasma_applet_org.kde.plasma.keyboardlayout
%find_lang plasma_applet_org.kde.plasma.kicker
%find_lang plasma_applet_org.kde.plasma.kickoff
%find_lang plasma_applet_org.kde.plasma.kimpanel
%find_lang plasma_applet_org.kde.plasma.minimizeall
%find_lang plasma_applet_org.kde.plasma.pager
%find_lang plasma_applet_org.kde.plasma.showActivityManager
%find_lang plasma_applet_org.kde.plasma.showdesktop
%find_lang plasma_applet_org.kde.plasma.taskmanager
%find_lang plasma_applet_org.kde.plasma.trash
%find_lang plasma_applet_org.kde.plasma.windowlist
%find_lang plasma_runner_kwin
%find_lang plasma_runner_plasma-desktop
%find_lang plasma_shell_org.kde.plasma.desktop
%find_lang plasma_toolbox_org.kde.desktoptoolbox
%find_lang plasma_toolbox_org.kde.paneltoolbox
%find_lang plasmaactivitymanager
## install_append content
#mv %{buildroot}/etc/dbus-1/* %{buildroot}/usr/share/dbus-1/
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/libexec/kauth/kcmdatetimehelper
/usr/lib64/libexec/kimpanel-ibus-panel
/usr/lib64/libexec/kimpanel-ibus-panel-launcher

%files bin
%defattr(-,root,root,-)
/usr/bin/ibus-ui-emojier-plasma
/usr/bin/kaccess
/usr/bin/kapplymousetheme
/usr/bin/kcm-touchpad-list-devices
/usr/bin/knetattach
/usr/bin/krunner-plugininstaller
/usr/bin/solid-action-desktop-gen
/usr/bin/tastenbrett

%files data
%defattr(-,root,root,-)
/usr/share/applications/kcm_access.desktop
/usr/share/applications/kcm_activities.desktop
/usr/share/applications/kcm_baloofile.desktop
/usr/share/applications/kcm_clock.desktop
/usr/share/applications/kcm_componentchooser.desktop
/usr/share/applications/kcm_desktoppaths.desktop
/usr/share/applications/kcm_device_automounter.desktop
/usr/share/applications/kcm_joystick.desktop
/usr/share/applications/kcm_kded.desktop
/usr/share/applications/kcm_keyboard.desktop
/usr/share/applications/kcm_keys.desktop
/usr/share/applications/kcm_krunnersettings.desktop
/usr/share/applications/kcm_launchfeedback.desktop
/usr/share/applications/kcm_mouse.desktop
/usr/share/applications/kcm_plasmasearch.desktop
/usr/share/applications/kcm_qtquicksettings.desktop
/usr/share/applications/kcm_smserver.desktop
/usr/share/applications/kcm_solid_actions.desktop
/usr/share/applications/kcm_splashscreen.desktop
/usr/share/applications/kcm_tablet.desktop
/usr/share/applications/kcm_touchpad.desktop
/usr/share/applications/kcm_workspace.desktop
/usr/share/applications/kcmspellchecking.desktop
/usr/share/applications/org.kde.knetattach.desktop
/usr/share/applications/org.kde.plasma.emojier.desktop
/usr/share/config.kcfg/kactivitymanagerd_plugins_settings.kcfg
/usr/share/config.kcfg/kactivitymanagerd_settings.kcfg
/usr/share/config.kcfg/kcmaccessibilitybell.kcfg
/usr/share/config.kcfg/kcmaccessibilitykeyboard.kcfg
/usr/share/config.kcfg/kcmaccessibilitymouse.kcfg
/usr/share/config.kcfg/kcmaccessibilityscreenreader.kcfg
/usr/share/config.kcfg/krunnersettingsbase.kcfg
/usr/share/config.kcfg/landingpage_kdeglobalssettings.kcfg
/usr/share/config.kcfg/launchfeedbacksettingsbase.kcfg
/usr/share/config.kcfg/splashscreensettings.kcfg
/usr/share/config.kcfg/workspaceoptions_kdeglobalssettings.kcfg
/usr/share/config.kcfg/workspaceoptions_kwinsettings.kcfg
/usr/share/config.kcfg/workspaceoptions_plasmasettings.kcfg
/usr/share/dbus-1/interfaces/org.kde.touchpad.xml
/usr/share/dbus-1/system-services/org.kde.kcontrol.kcmclock.service
/usr/share/dbus-1/system.d/org.kde.kcontrol.kcmclock.conf
/usr/share/icons/hicolor/128x128/devices/input-touchpad.png
/usr/share/icons/hicolor/16x16/devices/input-touchpad.png
/usr/share/icons/hicolor/22x22/devices/input-touchpad.png
/usr/share/icons/hicolor/24x24/devices/input-touchpad.png
/usr/share/icons/hicolor/256x256/devices/input-touchpad.png
/usr/share/icons/hicolor/32x32/devices/input-touchpad.png
/usr/share/icons/hicolor/48x48/devices/input-touchpad.png
/usr/share/icons/hicolor/64x64/devices/input-touchpad.png
/usr/share/icons/hicolor/96x96/devices/input-touchpad.png
/usr/share/icons/hicolor/scalable/devices/input-touchpad.svgz
/usr/share/kcmkeys/kde3.kksrc
/usr/share/kcmkeys/kde4.kksrc
/usr/share/kcmkeys/mac4.kksrc
/usr/share/kcmkeys/unix3.kksrc
/usr/share/kcmkeys/win3.kksrc
/usr/share/kcmkeys/win4.kksrc
/usr/share/kcmkeys/wm3.kksrc
/usr/share/kcmmouse/cursor_large_black.pcf.gz
/usr/share/kcmmouse/cursor_large_white.pcf.gz
/usr/share/kcmmouse/cursor_small_white.pcf.gz
/usr/share/kcmmouse/pics/mouse_lh.png
/usr/share/kcmmouse/pics/mouse_rh.png
/usr/share/kcmsolidactions/solid-action-template.desktop
/usr/share/kconf_update/kcm_rename_plasma_desktop.sh
/usr/share/kconf_update/kcm_rename_plasma_desktop.upd
/usr/share/kconf_update/kcminputrc_fix_botched_5_21_0.py
/usr/share/kconf_update/kcminputrc_fix_botched_5_21_0.upd
/usr/share/kconf_update/kcminputrc_migrate_repeat_value.py
/usr/share/kconf_update/kcminputrc_repeat.upd
/usr/share/kconf_update/ksmserver_update_loginMode_value.py
/usr/share/kconf_update/ksmserver_update_loginMode_value.upd
/usr/share/kconf_update/kxkb.upd
/usr/share/kconf_update/kxkb_emptylists.awk
/usr/share/kconf_update/kxkb_resetoptions.awk
/usr/share/kconf_update/kxkb_variants.awk
/usr/share/kconf_update/kxkb_variants.upd
/usr/share/kf5/kactivitymanagerd/workspace/settings/qml/activitiesTab/ActivitiesView.qml
/usr/share/kf5/kactivitymanagerd/workspace/settings/qml/activitiesTab/main.qml
/usr/share/kf5/kactivitymanagerd/workspace/settings/qml/activityDialog/GeneralTab.qml
/usr/share/kf5/kactivitymanagerd/workspace/settings/qml/privacyTab/BlacklistApplicationView.qml
/usr/share/kglobalaccel/org.kde.plasma.emojier.desktop
/usr/share/knotifications5/kaccess.notifyrc
/usr/share/knotifications5/kcm_touchpad.notifyrc
/usr/share/knsrcfiles/krunner.knsrc
/usr/share/knsrcfiles/ksplash.knsrc
/usr/share/kpackage/kcms/kcm5_kded/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_access/contents/ui/Bell.qml
/usr/share/kpackage/kcms/kcm_access/contents/ui/KeyboardFilters.qml
/usr/share/kpackage/kcms/kcm_access/contents/ui/ModifierKeys.qml
/usr/share/kpackage/kcms/kcm_access/contents/ui/MouseNavigation.qml
/usr/share/kpackage/kcms/kcm_access/contents/ui/ScreenReader.qml
/usr/share/kpackage/kcms/kcm_access/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_baloofile/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_componentchooser/contents/ui/ComponentComboBox.qml
/usr/share/kpackage/kcms/kcm_componentchooser/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_keys/contents/ui/ShortcutActionDelegate.qml
/usr/share/kpackage/kcms/kcm_keys/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_krunnersettings/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_landingpage/contents/ui/FeedbackControls.qml
/usr/share/kpackage/kcms/kcm_landingpage/contents/ui/MostUsedIcon.qml
/usr/share/kpackage/kcms/kcm_landingpage/contents/ui/Thumbnail.qml
/usr/share/kpackage/kcms/kcm_landingpage/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_launchfeedback/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_smserver/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_splashscreen/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_tablet/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_workspace/contents/ui/main.qml
/usr/share/kservicetypes5/solid-device-type.desktop
/usr/share/locale/sr/LC_SCRIPTS/kfontinst/kfontinst.js
/usr/share/locale/sr@ijekavian/LC_SCRIPTS/kfontinst/kfontinst.js
/usr/share/locale/sr@ijekavianlatin/LC_SCRIPTS/kfontinst/kfontinst.js
/usr/share/locale/sr@latin/LC_SCRIPTS/kfontinst/kfontinst.js
/usr/share/metainfo/org.kde.desktopcontainment.appdata.xml
/usr/share/metainfo/org.kde.desktoptoolbox.appdata.xml
/usr/share/metainfo/org.kde.paneltoolbox.appdata.xml
/usr/share/metainfo/org.kde.plasma.desktop.appdata.xml
/usr/share/metainfo/org.kde.plasma.desktop.appmenubar.appdata.xml
/usr/share/metainfo/org.kde.plasma.desktop.defaultPanel.appdata.xml
/usr/share/metainfo/org.kde.plasma.desktop.emptyPanel.appdata.xml
/usr/share/metainfo/org.kde.plasma.folder.appdata.xml
/usr/share/metainfo/org.kde.plasma.icontasks.appdata.xml
/usr/share/metainfo/org.kde.plasma.keyboardlayout.appdata.xml
/usr/share/metainfo/org.kde.plasma.kicker.appdata.xml
/usr/share/metainfo/org.kde.plasma.kickoff.appdata.xml
/usr/share/metainfo/org.kde.plasma.kimpanel.appdata.xml
/usr/share/metainfo/org.kde.plasma.marginsseparator.appdata.xml
/usr/share/metainfo/org.kde.plasma.minimizeall.appdata.xml
/usr/share/metainfo/org.kde.plasma.pager.appdata.xml
/usr/share/metainfo/org.kde.plasma.showActivityManager.appdata.xml
/usr/share/metainfo/org.kde.plasma.showdesktop.appdata.xml
/usr/share/metainfo/org.kde.plasma.taskmanager.appdata.xml
/usr/share/metainfo/org.kde.plasma.trash.appdata.xml
/usr/share/metainfo/org.kde.plasma.windowlist.appdata.xml
/usr/share/metainfo/org.kde.plasmashell.metainfo.xml
/usr/share/plasma/desktoptheme/default/icons/touchpad.svg
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.appmenubar/contents/layout.js
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.appmenubar/metadata.json
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/contents/layout.js
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/metadata.json
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.emptyPanel/contents/layout.js
/usr/share/plasma/layout-templates/org.kde.plasma.desktop.emptyPanel/metadata.json
/usr/share/plasma/packages/org.kde.desktoptoolbox/contents/config/main.xml
/usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxContent.qml
/usr/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxRoot.qml
/usr/share/plasma/packages/org.kde.desktoptoolbox/metadata.json
/usr/share/plasma/packages/org.kde.paneltoolbox/contents/ui/main.qml
/usr/share/plasma/packages/org.kde.paneltoolbox/metadata.json
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ActionButton.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/BackButtonItem.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/BusyOverlay.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ConfigFilter.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ConfigIcons.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ConfigLocation.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/ConfigOverlay.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemActionButton.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemPreviewPluginsDialog.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderView.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderViewDialog.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderViewDropArea.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderViewLayer.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/code/FolderTools.js
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.desktopcontainment/metadata.json
/usr/share/plasma/plasmoids/org.kde.panel/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.panel/contents/ui/ConfigOverlay.qml
/usr/share/plasma/plasmoids/org.kde.panel/contents/ui/LayoutManager.js
/usr/share/plasma/plasmoids/org.kde.panel/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.panel/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.folder/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.icontasks/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardlayout/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardlayout/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardlayout/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardlayout/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.keyboardlayout/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ActionMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ConfigGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/DashboardRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/DashboardTabBar.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/DashboardTabButton.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemGridDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemGridView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemListDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemListDialog.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemListView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/ItemMultiGridView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/MenuRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/RunnerResultsList.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/SideBarItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/SideBarSection.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/code/tools.js
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kicker/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/ActionMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/ApplicationsPage.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/BasePage.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/ConfigGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/DropAreaGridView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/DropAreaListView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/EmptyPage.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Footer.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/FullRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Header.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/HorizontalStackView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Kickoff.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffDropArea.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffGridView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffItemDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffListView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/KickoffSingleton.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/LeaveButtons.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/NormalPage.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/PlacesPage.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/VerticalStackView.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/code/tools.js
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/qmldir
/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/ActionMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/CandidateHighlight.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/ConfigAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/ContextMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/InputPanel.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/StatusIcon.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.kimpanel/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.marginsseparator/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.marginsseparator/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.marginsseparator/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.marginsseparator/package/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.marginsseparator/package/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.marginsseparator/package/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.marginsseparator/plugin/marginSeparator.cpp
/usr/share/plasma/plasmoids/org.kde.plasma.marginsseparator/plugin/marginSeparator.h
/usr/share/plasma/plasmoids/org.kde.plasma.minimizeall/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.minimizeall/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.minimizeall/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.pager/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.pager/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.pager/contents/ui/configGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.pager/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.pager/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.showActivityManager/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.showActivityManager/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.showActivityManager/contents/ui/ConfigAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.showActivityManager/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.showActivityManager/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.showdesktop/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.showdesktop/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.showdesktop/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/AudioStream.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Badge.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ConfigAppearance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ConfigBehavior.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ContextMenu.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/GroupDialog.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/GroupExpanderOverlay.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/MouseHandler.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/PipeWireThumbnail.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/PlayerController.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/PulseAudio.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ScrollableTextWrapper.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/TaskBadgeOverlay.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/TaskList.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/TaskProgressOverlay.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ToolTipDelegate.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ToolTipInstance.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/ToolTipWindowMouseArea.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/code/layout.js
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/code/tools.js
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.trash/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.trash/metadata.json
/usr/share/plasma/plasmoids/org.kde.plasma.windowlist/contents/ui/MenuButton.qml
/usr/share/plasma/plasmoids/org.kde.plasma.windowlist/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.windowlist/metadata.json
/usr/share/plasma/plasmoids/touchpad/contents/ui/touchpad.qml
/usr/share/plasma/plasmoids/touchpad/metadata.json
/usr/share/plasma/services/touchpad.operations
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/InteractiveConsole.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/ActivityItem.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/ActivityList.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/ActivityManager.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/Heading.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/StoppedActivityItem.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/TaskDropArea.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/WindowPreview.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/activitymanager/static.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/applet/AppletError.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/applet/CompactApplet.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/applet/DefaultCompactRepresentation.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AboutPlugin.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigCategoryDelegate.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationAppletPage.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentActions.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationKcmPage.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationShortcuts.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ContainmentConfiguration.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/MouseEventInputButton.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/PanelConfiguration.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ShellContainmentConfiguration.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/MoreSettingsMenu.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/Ruler.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/SliderHandle.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/ToolBar.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/shellcontainmentconfiguration/Delegate.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/defaults
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletAlternatives.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/Tooltip.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/WidgetExplorer.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/layout.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/containmentactions_middlebutton.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/digitalclock_rename_timezonedisplay_key.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/klipper_clear_config.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/maintain_existing_desktop_icon_sizes.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/move_desktop_layout_config.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/no_middle_click_paste_on_panels.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/systemloadviewer_systemmonitor.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/unlock_widgets.js
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml
/usr/share/plasma/shells/org.kde.plasma.desktop/metadata.json
/usr/share/polkit-1/actions/org.kde.kcontrol.kcmclock.policy
/usr/share/qlogging-categories5/kcm_kded.categories
/usr/share/qlogging-categories5/kcm_keyboard.categories
/usr/share/qlogging-categories5/kcm_mouse.categories
/usr/share/qlogging-categories5/kcm_tablet.categories
/usr/share/qlogging-categories5/kcmkeys.categories
/usr/share/solid/devices/solid-device-Battery.desktop
/usr/share/solid/devices/solid-device-Block.desktop
/usr/share/solid/devices/solid-device-Camera.desktop
/usr/share/solid/devices/solid-device-OpticalDisc.desktop
/usr/share/solid/devices/solid-device-OpticalDrive.desktop
/usr/share/solid/devices/solid-device-PortableMediaPlayer.desktop
/usr/share/solid/devices/solid-device-Processor.desktop
/usr/share/solid/devices/solid-device-StorageAccess.desktop
/usr/share/solid/devices/solid-device-StorageDrive.desktop
/usr/share/solid/devices/solid-device-StorageVolume.desktop
/usr/share/xdg/autostart/kaccess.desktop

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/ca/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/clock/index.docbook
/usr/share/doc/HTML/ca/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/ca/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/ca/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmactivities/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmactivities/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kded/index.docbook
/usr/share/doc/HTML/ca/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/ca/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/keys/index.docbook
/usr/share/doc/HTML/ca/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/ca/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/paths/index.docbook
/usr/share/doc/HTML/ca/kcontrol/paths/paths.png
/usr/share/doc/HTML/ca/kcontrol/solid-actions/add-action.png
/usr/share/doc/HTML/ca/kcontrol/solid-actions/edit-action.png
/usr/share/doc/HTML/ca/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/ca/kcontrol/solid-actions/main.png
/usr/share/doc/HTML/ca/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/ca/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/ca/kcontrol/splashscreen/get-new-theme.png
/usr/share/doc/HTML/ca/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/ca/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/ca/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/ca/kfontview/index.cache.bz2
/usr/share/doc/HTML/ca/kfontview/index.docbook
/usr/share/doc/HTML/ca/kfontview/kfontview.png
/usr/share/doc/HTML/ca/knetattach/index.cache.bz2
/usr/share/doc/HTML/ca/knetattach/index.docbook
/usr/share/doc/HTML/ca/knetattach/screenshot.png
/usr/share/doc/HTML/ca/knetattach/screenshot1.png
/usr/share/doc/HTML/ca/knetattach/screenshot2.png
/usr/share/doc/HTML/ca/knetattach/screenshot3.png
/usr/share/doc/HTML/ca/knetattach/screenshot4.png
/usr/share/doc/HTML/ca/plasma-desktop/add-widgets.png
/usr/share/doc/HTML/ca/plasma-desktop/application-launcher.png
/usr/share/doc/HTML/ca/plasma-desktop/application-menu.png
/usr/share/doc/HTML/ca/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/ca/plasma-desktop/index.docbook
/usr/share/doc/HTML/de/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/de/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/clock/index.docbook
/usr/share/doc/HTML/de/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/de/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/de/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmactivities/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmactivities/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/de/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kded/index.docbook
/usr/share/doc/HTML/de/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/de/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/keys/index.docbook
/usr/share/doc/HTML/de/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/de/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/paths/index.docbook
/usr/share/doc/HTML/de/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/de/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/de/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/de/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/de/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/de/kfontview/index.cache.bz2
/usr/share/doc/HTML/de/kfontview/index.docbook
/usr/share/doc/HTML/de/knetattach/index.cache.bz2
/usr/share/doc/HTML/de/knetattach/index.docbook
/usr/share/doc/HTML/de/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/de/plasma-desktop/index.docbook
/usr/share/doc/HTML/en/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/en/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/clock/index.docbook
/usr/share/doc/HTML/en/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/en/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/en/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/en/kcontrol/joystick/joystick-calibration.png
/usr/share/doc/HTML/en/kcontrol/joystick/joystick-main.png
/usr/share/doc/HTML/en/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/en/kcontrol/kcmactivities/configure.png
/usr/share/doc/HTML/en/kcontrol/kcmactivities/edit-delete.png
/usr/share/doc/HTML/en/kcontrol/kcmactivities/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmactivities/index.docbook
/usr/share/doc/HTML/en/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/en/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/en/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kded/index.docbook
/usr/share/doc/HTML/en/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/en/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/keys/index.docbook
/usr/share/doc/HTML/en/kcontrol/keys/list-add.png
/usr/share/doc/HTML/en/kcontrol/keys/remove.png
/usr/share/doc/HTML/en/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/en/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/paths/index.docbook
/usr/share/doc/HTML/en/kcontrol/paths/paths.png
/usr/share/doc/HTML/en/kcontrol/solid-actions/add-action.png
/usr/share/doc/HTML/en/kcontrol/solid-actions/edit-action.png
/usr/share/doc/HTML/en/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/en/kcontrol/solid-actions/main.png
/usr/share/doc/HTML/en/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/en/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/en/kcontrol/splashscreen/get-new-theme.png
/usr/share/doc/HTML/en/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/en/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/en/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/en/kfontview/index.cache.bz2
/usr/share/doc/HTML/en/kfontview/index.docbook
/usr/share/doc/HTML/en/kfontview/kfontview.png
/usr/share/doc/HTML/en/knetattach/index.cache.bz2
/usr/share/doc/HTML/en/knetattach/index.docbook
/usr/share/doc/HTML/en/knetattach/screenshot.png
/usr/share/doc/HTML/en/knetattach/screenshot1.png
/usr/share/doc/HTML/en/knetattach/screenshot2.png
/usr/share/doc/HTML/en/knetattach/screenshot3.png
/usr/share/doc/HTML/en/knetattach/screenshot4.png
/usr/share/doc/HTML/en/plasma-desktop/add-widgets.png
/usr/share/doc/HTML/en/plasma-desktop/application-launcher-settings.png
/usr/share/doc/HTML/en/plasma-desktop/application-launcher.png
/usr/share/doc/HTML/en/plasma-desktop/application-menu.png
/usr/share/doc/HTML/en/plasma-desktop/desktop-settings.png
/usr/share/doc/HTML/en/plasma-desktop/device_notifier_widget.png
/usr/share/doc/HTML/en/plasma-desktop/device_notifier_widget_actions.png
/usr/share/doc/HTML/en/plasma-desktop/folder-view.png
/usr/share/doc/HTML/en/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/en/plasma-desktop/index.docbook
/usr/share/doc/HTML/en/plasma-desktop/krunner-configure.png
/usr/share/doc/HTML/en/plasma-desktop/krunner-desktop-actions.png
/usr/share/doc/HTML/en/plasma-desktop/krunner.png
/usr/share/doc/HTML/en/plasma-desktop/panel-settings.png
/usr/share/doc/HTML/en/plasma-desktop/plasma-desktop-annotated.png
/usr/share/doc/HTML/en/plasma-desktop/remove.png
/usr/share/doc/HTML/en/plasma-desktop/system-tray-settings.png
/usr/share/doc/HTML/en/plasma-desktop/system-tray-up-arrow.png
/usr/share/doc/HTML/en/plasma-desktop/taskbar-settings.png
/usr/share/doc/HTML/es/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/es/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/clock/index.docbook
/usr/share/doc/HTML/es/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/es/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/es/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/es/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/es/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/es/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kded/index.docbook
/usr/share/doc/HTML/es/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/es/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/paths/index.docbook
/usr/share/doc/HTML/es/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/es/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/es/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/es/kfontview/index.cache.bz2
/usr/share/doc/HTML/es/kfontview/index.docbook
/usr/share/doc/HTML/es/knetattach/index.cache.bz2
/usr/share/doc/HTML/es/knetattach/index.docbook
/usr/share/doc/HTML/et/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/clock/index.docbook
/usr/share/doc/HTML/et/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/et/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/id/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/id/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/clock/index.docbook
/usr/share/doc/HTML/id/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/id/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/id/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/id/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/id/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/id/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/id/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kded/index.docbook
/usr/share/doc/HTML/id/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/id/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/keys/index.docbook
/usr/share/doc/HTML/id/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/id/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/paths/index.docbook
/usr/share/doc/HTML/id/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/id/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/id/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/id/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/id/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/id/kfontview/index.cache.bz2
/usr/share/doc/HTML/id/kfontview/index.docbook
/usr/share/doc/HTML/id/knetattach/index.cache.bz2
/usr/share/doc/HTML/id/knetattach/index.docbook
/usr/share/doc/HTML/id/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/id/plasma-desktop/index.docbook
/usr/share/doc/HTML/it/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/it/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/clock/index.docbook
/usr/share/doc/HTML/it/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/it/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/it/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmactivities/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmactivities/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/it/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kded/index.docbook
/usr/share/doc/HTML/it/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/it/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/keys/index.docbook
/usr/share/doc/HTML/it/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/it/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/paths/index.docbook
/usr/share/doc/HTML/it/kcontrol/solid-actions/add-action.png
/usr/share/doc/HTML/it/kcontrol/solid-actions/edit-action.png
/usr/share/doc/HTML/it/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/it/kcontrol/solid-actions/main.png
/usr/share/doc/HTML/it/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/it/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/it/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/it/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/it/kfontview/index.cache.bz2
/usr/share/doc/HTML/it/kfontview/index.docbook
/usr/share/doc/HTML/it/knetattach/index.cache.bz2
/usr/share/doc/HTML/it/knetattach/index.docbook
/usr/share/doc/HTML/it/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/it/plasma-desktop/index.docbook
/usr/share/doc/HTML/nl/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/nl/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/clock/index.docbook
/usr/share/doc/HTML/nl/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/nl/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/nl/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmactivities/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmactivities/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kded/index.docbook
/usr/share/doc/HTML/nl/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/nl/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/keys/index.docbook
/usr/share/doc/HTML/nl/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/nl/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/paths/index.docbook
/usr/share/doc/HTML/nl/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/nl/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/nl/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/nl/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/nl/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/nl/kfontview/index.cache.bz2
/usr/share/doc/HTML/nl/kfontview/index.docbook
/usr/share/doc/HTML/nl/knetattach/index.cache.bz2
/usr/share/doc/HTML/nl/knetattach/index.docbook
/usr/share/doc/HTML/nl/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/nl/plasma-desktop/index.docbook
/usr/share/doc/HTML/pt/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/pt/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/clock/index.docbook
/usr/share/doc/HTML/pt/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/pt/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/pt/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kded/index.docbook
/usr/share/doc/HTML/pt/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/pt/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/keys/index.docbook
/usr/share/doc/HTML/pt/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/pt/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/paths/index.docbook
/usr/share/doc/HTML/pt/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/pt/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/pt/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/pt/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/pt/kfontview/index.cache.bz2
/usr/share/doc/HTML/pt/kfontview/index.docbook
/usr/share/doc/HTML/pt/knetattach/index.cache.bz2
/usr/share/doc/HTML/pt/knetattach/index.docbook
/usr/share/doc/HTML/pt/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/pt/plasma-desktop/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/clock/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kded/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/keys/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/paths/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/pt_BR/kfontview/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kfontview/index.docbook
/usr/share/doc/HTML/pt_BR/knetattach/index.cache.bz2
/usr/share/doc/HTML/pt_BR/knetattach/index.docbook
/usr/share/doc/HTML/pt_BR/knetattach/screenshot.png
/usr/share/doc/HTML/pt_BR/knetattach/screenshot1.png
/usr/share/doc/HTML/pt_BR/knetattach/screenshot2.png
/usr/share/doc/HTML/pt_BR/knetattach/screenshot3.png
/usr/share/doc/HTML/pt_BR/knetattach/screenshot4.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/add-widgets.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/desktop-settings.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/pt_BR/plasma-desktop/index.docbook
/usr/share/doc/HTML/pt_BR/plasma-desktop/krunner-configure.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/krunner.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/panel-settings.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/system-tray-settings.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/system-tray-up-arrow.png
/usr/share/doc/HTML/pt_BR/plasma-desktop/taskbar-settings.png
/usr/share/doc/HTML/ru/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/ru/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/clock/index.docbook
/usr/share/doc/HTML/ru/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/ru/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/ru/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/ru/kcontrol/joystick/joystick-calibration.png
/usr/share/doc/HTML/ru/kcontrol/joystick/joystick-main.png
/usr/share/doc/HTML/ru/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kcmactivities/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmactivities/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kded/index.docbook
/usr/share/doc/HTML/ru/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/ru/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/keys/index.docbook
/usr/share/doc/HTML/ru/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/ru/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/paths/index.docbook
/usr/share/doc/HTML/ru/kcontrol/paths/paths.png
/usr/share/doc/HTML/ru/kcontrol/solid-actions/add-action.png
/usr/share/doc/HTML/ru/kcontrol/solid-actions/edit-action.png
/usr/share/doc/HTML/ru/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/ru/kcontrol/solid-actions/main.png
/usr/share/doc/HTML/ru/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/ru/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/ru/kcontrol/splashscreen/get-new-theme.png
/usr/share/doc/HTML/ru/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/ru/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/ru/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/ru/kfontview/index.cache.bz2
/usr/share/doc/HTML/ru/kfontview/index.docbook
/usr/share/doc/HTML/ru/knetattach/index.cache.bz2
/usr/share/doc/HTML/ru/knetattach/index.docbook
/usr/share/doc/HTML/ru/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/ru/plasma-desktop/index.docbook
/usr/share/doc/HTML/sr/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/clock/index.docbook
/usr/share/doc/HTML/sr/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/sr/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/paths/index.docbook
/usr/share/doc/HTML/sr/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/sr/knetattach/index.cache.bz2
/usr/share/doc/HTML/sr/knetattach/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/clock/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/paths/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/sr@latin/knetattach/index.cache.bz2
/usr/share/doc/HTML/sr@latin/knetattach/index.docbook
/usr/share/doc/HTML/sv/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/sv/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/clock/index.docbook
/usr/share/doc/HTML/sv/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/sv/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/sv/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmactivities/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmactivities/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kded/index.docbook
/usr/share/doc/HTML/sv/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/sv/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/keys/index.docbook
/usr/share/doc/HTML/sv/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/sv/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/paths/index.docbook
/usr/share/doc/HTML/sv/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/sv/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/sv/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/sv/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/sv/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/sv/kfontview/index.cache.bz2
/usr/share/doc/HTML/sv/kfontview/index.docbook
/usr/share/doc/HTML/sv/knetattach/index.cache.bz2
/usr/share/doc/HTML/sv/knetattach/index.docbook
/usr/share/doc/HTML/sv/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/sv/plasma-desktop/index.docbook
/usr/share/doc/HTML/uk/kcontrol/baloo/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/baloo/index.docbook
/usr/share/doc/HTML/uk/kcontrol/clock/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/clock/index.docbook
/usr/share/doc/HTML/uk/kcontrol/componentchooser/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/componentchooser/index.docbook
/usr/share/doc/HTML/uk/kcontrol/cursortheme/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/cursortheme/index.docbook
/usr/share/doc/HTML/uk/kcontrol/joystick/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/joystick/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmaccess/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmaccess/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmactivities/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmactivities/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmlaunchfeedback/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmlaunchfeedback/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmsmserver/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmsmserver/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kded/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kded/index.docbook
/usr/share/doc/HTML/uk/kcontrol/keyboard/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/keyboard/index.docbook
/usr/share/doc/HTML/uk/kcontrol/keys/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/keys/index.docbook
/usr/share/doc/HTML/uk/kcontrol/mouse/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/mouse/index.docbook
/usr/share/doc/HTML/uk/kcontrol/paths/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/paths/index.docbook
/usr/share/doc/HTML/uk/kcontrol/paths/paths.png
/usr/share/doc/HTML/uk/kcontrol/solid-actions/add-action.png
/usr/share/doc/HTML/uk/kcontrol/solid-actions/edit-action.png
/usr/share/doc/HTML/uk/kcontrol/solid-actions/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/solid-actions/index.docbook
/usr/share/doc/HTML/uk/kcontrol/solid-actions/main.png
/usr/share/doc/HTML/uk/kcontrol/solid-device-automounter/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/solid-device-automounter/index.docbook
/usr/share/doc/HTML/uk/kcontrol/spellchecking/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/spellchecking/index.docbook
/usr/share/doc/HTML/uk/kcontrol/splashscreen/get-new-theme.png
/usr/share/doc/HTML/uk/kcontrol/splashscreen/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/splashscreen/index.docbook
/usr/share/doc/HTML/uk/kcontrol/splashscreen/splash-main.png
/usr/share/doc/HTML/uk/kcontrol/workspaceoptions/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/workspaceoptions/index.docbook
/usr/share/doc/HTML/uk/kfontview/index.cache.bz2
/usr/share/doc/HTML/uk/kfontview/index.docbook
/usr/share/doc/HTML/uk/kfontview/kfontview.png
/usr/share/doc/HTML/uk/knetattach/index.cache.bz2
/usr/share/doc/HTML/uk/knetattach/index.docbook
/usr/share/doc/HTML/uk/plasma-desktop/application-launcher-settings.png
/usr/share/doc/HTML/uk/plasma-desktop/index.cache.bz2
/usr/share/doc/HTML/uk/plasma-desktop/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kf5/kded/device_automounter.so
/usr/lib64/qt5/plugins/kf5/kded/kded_touchpad.so
/usr/lib64/qt5/plugins/kf5/kded/keyboard.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_kwin.so
/usr/lib64/qt5/plugins/kf5/krunner/krunner_plasma-desktop.so
/usr/lib64/qt5/plugins/plasma/applets/org.kde.plasma.marginsseparator.so
/usr/lib64/qt5/plugins/plasma/dataengine/plasma_engine_touchpad.so
/usr/lib64/qt5/plugins/plasma/kcminit/kcm_mouse_init.so
/usr/lib64/qt5/plugins/plasma/kcminit/kcm_touchpad_init.so
/usr/lib64/qt5/plugins/plasma/kcms/desktop/kcm_krunnersettings.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_access.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_baloofile.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_componentchooser.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_kded.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_keyboard.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_keys.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_landingpage.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_launchfeedback.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_mouse.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_smserver.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_splashscreen.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_tablet.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_touchpad.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_workspace.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_activities.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_clock.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_desktoppaths.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_device_automounter.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_joystick.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_plasmasearch.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_qtquicksettings.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_solid_actions.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcmspellchecking.so
/usr/lib64/qt5/qml/org/kde/activities/settings/libkactivitiessettingsplugin.so
/usr/lib64/qt5/qml/org/kde/activities/settings/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/activityswitcher/libactivityswitcherextensionplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/activityswitcher/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/emoji/libEmojierDeclarativePlugin.so
/usr/lib64/qt5/qml/org/kde/plasma/emoji/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/kimpanel/libkimpanelplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/kimpanel/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/pager/libpagerplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/pager/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/showdesktop/libshowdesktopplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/showdesktop/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/taskmanager/libtaskmanagerplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/taskmanager/qmldir
/usr/lib64/qt5/qml/org/kde/plasma/private/trash/libtrashplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/trash/qmldir
/usr/lib64/qt5/qml/org/kde/private/desktopcontainment/desktop/libdesktopplugin.so
/usr/lib64/qt5/qml/org/kde/private/desktopcontainment/desktop/qmldir
/usr/lib64/qt5/qml/org/kde/private/desktopcontainment/folder/libfolderplugin.so
/usr/lib64/qt5/qml/org/kde/private/desktopcontainment/folder/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plasma-desktop/19d98e1b6f8ef12849ea4012a052d3907f336c91
/usr/share/package-licenses/plasma-desktop/2123756e0b1fc8243547235a33c0fcabfe3b9a51
/usr/share/package-licenses/plasma-desktop/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/plasma-desktop/57c3cb6b9aee09ae2af06b0c517e2969d2f33d47
/usr/share/package-licenses/plasma-desktop/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/plasma-desktop/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/plasma-desktop/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/plasma-desktop/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/plasma-desktop/a4c60b3fefda228cd7439d3565df043192fef137
/usr/share/package-licenses/plasma-desktop/bd75d59f9d7d9731bfabdc48ecd19e704d218e38
/usr/share/package-licenses/plasma-desktop/d08cb4fd7d3ab2539fc98f64d2c713453dfe46b5
/usr/share/package-licenses/plasma-desktop/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/plasma-desktop/ee03d68f6be20b170e5ea5d114d6acafb3f2d1dc

%files locales -f kaccess.lang -f kcm5_joystick.lang -f kcm5_kded.lang -f kcm_access.lang -f kcm_componentchooser.lang -f kcm_desktoppaths.lang -f kcm_launchfeedback.lang -f kcm_smserver.lang -f kcmkclock.lang -f kcmkeyboard.lang -f kcmmouse.lang -f knetattach5.lang -f plasma_applet_org.kde.desktopcontainment.lang -f kcm5_device_automounter.lang -f kcm_activities5.lang -f kcm_baloofile.lang -f kcm_keys.lang -f kcm_krunnersettings.lang -f kcm_landingpage.lang -f kcm_search.lang -f kcm_solid_actions.lang -f kcm_splashscreen.lang -f kcm_tablet.lang -f kcm_touchpad.lang -f kcm_workspace.lang -f kcmqtquicksettings.lang -f org.kde.plasma.emojier.lang -f plasma_applet_org.kde.panel.lang -f plasma_applet_org.kde.plasma.keyboardlayout.lang -f plasma_applet_org.kde.plasma.kicker.lang -f plasma_applet_org.kde.plasma.kickoff.lang -f plasma_applet_org.kde.plasma.kimpanel.lang -f plasma_applet_org.kde.plasma.minimizeall.lang -f plasma_applet_org.kde.plasma.pager.lang -f plasma_applet_org.kde.plasma.showActivityManager.lang -f plasma_applet_org.kde.plasma.showdesktop.lang -f plasma_applet_org.kde.plasma.taskmanager.lang -f plasma_applet_org.kde.plasma.trash.lang -f plasma_applet_org.kde.plasma.windowlist.lang -f plasma_runner_kwin.lang -f plasma_runner_plasma-desktop.lang -f plasma_shell_org.kde.plasma.desktop.lang -f plasma_toolbox_org.kde.desktoptoolbox.lang -f plasma_toolbox_org.kde.paneltoolbox.lang -f plasmaactivitymanager.lang
%defattr(-,root,root,-)

